### ISSUE TITLE
Investigation on Reveal OpenSRP Production Server Versions

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#1015]
CHAI encountered a number of odd server versions and would like us to investigate this. Below are the different occurences:

**Most recent plan in replica3:**

- Date: 11-25-2021
- ID: d54cf449-66ce-5e79-a8f4-f2ed48150d85
- serverVersion: 1601948157735

**Some examples of the 67 plans with higher server versions:**
- Oldest plan
-- Date: 2019-12-24
-- ID: f93b98c9-7f37-44db-843c-5eda07f581ae
-- serverVersion: 1601948157776
- Active plan
-- Date: 2021-05-19
-- ID: 1e485f9e-f934-5be8-8ec1-470caf42cf78
-- serverVersion: 1601948157770
- A draft (!) plan:
-- Date: 2021-09-07
-- ID: 9ac85804-8edd-46a8-834e-a63eeef036e5
-- serverVersion: 1601948157744

Several of these plans are listed as their first version which should indicate that they have not been updated since they were created. Any info you might have on what might be going on here would be useful

**Comment by Rkareko** [comment]
@samkanga the server versions for the above plans correspond to the dates they were edited as shown below

```
select identifier, json->>'date' plan_date, server_version, date_edited from core.plan where identifier in ('d54cf449-66ce-5e79-a8f4-f2ed48150d85','f93b98c9-7f37-44db-843c-5eda07f581ae','9ac85804-8edd-46a8-834e-a63eeef036e5') order by server_version desc;
              identifier              | plan_date  | server_version |       date_edited       
--------------------------------------+------------+----------------+-------------------------
 d54cf449-66ce-5e79-a8f4-f2ed48150d85 | 2021-11-25 |  1601948946404 | 2021-12-15 09:04:57.831
 9ac85804-8edd-46a8-834e-a63eeef036e5 | 2021-09-07 |  1601948688027 | 2021-12-05 12:02:07.341
 f93b98c9-7f37-44db-843c-5eda07f581ae | 2019-12-24 |  1601948157776 | 2021-11-25 19:50:10.879

```

**Comment by samkanga** [comment]
OK. Going ahead to close this ticket.
