### ISSUE TITLE
UNICEF Tunisia: Production Web configuration

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-server-web#1016]
OpenSRP configuration checklist

- [x] Set up unique Ids sources
- [x] Set up the root location
- [x] set up the default plan with the root location on the jurisdiction
- [x] Create a test user.
- [x] Create a user group (Superuser)
- [x] Create all required roles (Keycloak) -- OpenSRP web team to add all their required roles.
- [x] Create a test team.
- [x] Assign the user to the team
- [x] Assign the team to a location.
- [ ] These are required for both the app and the web instance

**Comment by dubdabasoduba** [comment]
@AnnieMungai I think this now complete.

**Comment by AnnieMungai** [comment]
Looking good!
