### ISSUE TITLE
Deletion of Duplicate Plans on Thailand Production OpenSRP Db

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#1018]
CHAI have shared a number fo plans that are deemed to be duplicates on the OpenSRP DB. Please assist in deleting the following plans:

1. c8da789a-2a4c-4138-a057-fa5bf07a6187
2. ca7f3d0b-cfb5-4bd9-bde6-7e59e9c860b4
3. 06536af5-61fb-4d9b-92e0-e2bd482b38e5
4. 7220a8d3-5149-4842-a32b-e21584a7dfc4
5. 0dc82b1a-e602-4bdb-80bb-8ebccbec2084
6. 1a1e5884-9d45-46f1-9fa5-ee7e8e5e7f94
7. 50a1dcfd-de61-45ad-9c9e-2e425579f7cb

**Comment by Rkareko** [comment]
@samkanga There is one active plan on that list. Will it also be deleted?

```
select json->>'status' status, identifier from core.plan 
where identifier in ('c8da789a-2a4c-4138-a057-fa5bf07a6187',
'ca7f3d0b-cfb5-4bd9-bde6-7e59e9c860b4',
'06536af5-61fb-4d9b-92e0-e2bd482b38e5',
'7220a8d3-5149-4842-a32b-e21584a7dfc4',
'0dc82b1a-e602-4bdb-80bb-8ebccbec2084',
'1a1e5884-9d45-46f1-9fa5-ee7e8e5e7f94',
'50a1dcfd-de61-45ad-9c9e-2e425579f7cb');
 status  |              identifier              
---------+--------------------------------------
 draft   | c8da789a-2a4c-4138-a057-fa5bf07a6187
 retired | 50a1dcfd-de61-45ad-9c9e-2e425579f7cb
 retired | ca7f3d0b-cfb5-4bd9-bde6-7e59e9c860b4
 draft   | 1a1e5884-9d45-46f1-9fa5-ee7e8e5e7f94
 draft   | 06536af5-61fb-4d9b-92e0-e2bd482b38e5
 active  | 0dc82b1a-e602-4bdb-80bb-8ebccbec2084
 draft   | 7220a8d3-5149-4842-a32b-e21584a7dfc4

```

**Comment by Rkareko** [comment]
@samkanga the plans have been deleted apart from `0dc82b1a-e602-4bdb-80bb-8ebccbec2084` which is active

**Comment by samkanga** [comment]
@Rkareko skip the plan for now.

**Comment by samkanga** [comment]
@Rkareko see additional plan below for deletion:

1. 33002d31-9782-4947-b0bd-cf09e0bffed8
2. 5d3db462-0e57-4f92-8f98-3925bcf7e719
3. 2d00d4bd-08f0-4dd2-ad4d-ef4cd50315c8
4. 8efda186-8993-4b31-aa62-5630b9c6e75f
5. 5e25dfa4-9979-4324-b0a0-e4dbe7a5c61d
6. f1cef218-7e4e-46e8-b548-68cbf67b3d28
7. 0dcaca17-066d-48eb-99d9-895b69d1ff23
8. 170c215f-0619-4772-a9de-b375a13ce827
9. a23c3e42-92a7-4a17-8e15-67924e68e089
10. 3dfb09d5-be2f-459d-be42-7f4f74be6122
11. 5d3db462-0e57-4f92-8f98-3925bcf7e719 - Active
12. 0dc82b1a-e602-4bdb-80bb-8ebccbec2084 - Active

**Comment by Rkareko** [comment]
@samkanga the duplicate plans have been deleted

**Comment by samkanga** [comment]
Marking this as completed.
