### ISSUE TITLE
Deletion of Duplicate Locations on Reveal Thailand Production OpenSRP DB

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#1019]
The following 2 locations have been reported to be duplicate and require deletion from the Thailand production OpenSPR DB. These are:
**Parent village**
- Location ID: `354fd11b-255b-42d1-868c-be37bb12da52`
- External ID: 86060204

 **Focus**
- Location ID: `cf7eb1e1-4949-4260-ae28-25942cfddf46`
- External ID: 8606020401

**Comment by Rkareko** [comment]
@samkanga the locations are not being returned by the opensrp API [354fd11b-255b-42d1-868c-be37bb12da52](https://servermhealth.ddc.moph.go.th/opensrp/rest/location/354fd11b-255b-42d1-868c-be37bb12da52?is_jurisdiction=true) and [cf7eb1e1-4949-4260-ae28-25942cfddf46](https://servermhealth.ddc.moph.go.th/opensrp/rest/location/cf7eb1e1-4949-4260-ae28-25942cfddf46?is_jurisdiction=true) .

They need to be removed from the canopy db

**Comment by samkanga** [comment]
Marking this as closed
