### ISSUE TITLE
Increase the Size Limit for Uploaded Product Catalogue Images

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#1033]
UNICEF Madagascar have encountered difficulties when uploading product catalogue images on the EUSM Web. The file size they were trying to upload was 1.4MB but would like to be allowed up to 5MB in image size. Is there a downside for this or can we comfortably accommodate this request?

**Comment by bennsimon** [comment]
Looks like a nginx config issue. Will increase the nginx max upload size.
