### ISSUE TITLE
Missing task alert generation issues on Thai - preview

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-server-web#1046]
Description.
issue related to [2163](https://github.com/onaio/canopy/issues/2163)
There is need to have alerts generated for plans that have missing tasks. 
It was implemented that [this](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/findMissingTaskGeneration?fromDate=2021-12-01) endpoint should fetch plans that have missing tasks.
The endpoint is fetching plans with missing tasks However there have been 2 issues noted:
1. Not all plans that have missing alerts are being fetched by the endpoint. e.g the plan below was not fetched.

```
77c0dc95-dcd1-46b4-bed5-67cd72bf3900 
removed RACD Blood screning action and RACD family register
```

 

2. Some data being fetched is incorrect i.e (wrong missing tasks showing.) e.g
```
A1 - เมืองทอง(Site)-4 - Madrine QA Test 7 - 2021-12-17 - Site
b75876f0-912c-4aa1-a34e-89d89ad8e165
removed RACD register family
```

see screenshot of the plan from the endpoint 
![image](https://user-images.githubusercontent.com/84722169/147104866-5efbf39c-b382-4ce2-b466-d13ad461a985.png)

Steps on how to replicate plans with missing tasks are explained [here](https://github.com/onaio/canopy/issues/2163#issuecomment-995530907)

**Comment by Rkareko** [comment]
The following are the tasks generated for the plan with Identifier `77c0dc95-dcd1-46b4-bed5-67cd72bf3900`


```
select count(*), code from core.task_metadata where plan_identifier = '77c0dc95-dcd1-46b4-bed5-67cd72bf3900' group by 2;
 count |        code         
-------+---------------------
    26 | Mosquito Collection
     1 | BCC
    23 | Larval Dipping
   103 | Bednet Distribution
(4 rows)
```

**Comment by madrinekariuki** [comment]
@Rkareko  cc @samkanga @ciremusyoka 
Retests have been made on this. 
please find below observations noted.

Plans used:

**Normal plan**
` 4d7187b3-1d06-5ccc-9e24-10ad134488e1`
removed
```
Register family
BS
```
observation:
missing tasks were picked by the endpoint and the alerts were also generated on the reveal logs channel.
screenshot:
![image](https://user-images.githubusercontent.com/84722169/148549347-137d5c65-a3dc-4aa6-a16a-2ef40035e51b.png)



**Case triggered plans:**
1.
` ff975b91-68e7-4550-8f61-a3100a6cb959`
Did not remove any tasks. NB no alerts expected for this one.
However an alert was raised showing missing Case confirmation task.
![image](https://user-images.githubusercontent.com/84722169/148550219-638aacbb-a7ff-481e-81cd-17ade17e164e.png)


2.
`d3f20435-6427-44b2-b012-e2b662688435`
Removed ALL Tasks i.e:
```
case confirmation
Register Family
BS
BCC
Bednest dist
larval dip
mos col
```
However alerts were only generated for 3 i.e  Case confirmation, BCC and Blood screening.
screenshot:
![image](https://user-images.githubusercontent.com/84722169/148549755-e82cffd7-6e01-4abc-83df-5d35a33ff192.png)

3.
`4bac463a-e38c-4cc0-9c03-3754a388d1f4`
removed BCC focus. thus only 1 alert should be generated However, Alert generated show that missing tasks are `Case confirmation` and `BCC`
`screenshot`
![image](https://user-images.githubusercontent.com/84722169/148550956-e35eee74-3b54-4545-9646-dde45a2fb5bd.png)


NB 
`d3f20435-6427-44b2-b012-e2b662688435 ` and `4bac463a-e38c-4cc0-9c03-3754a388d1f4` are source plans that are usually generated when a case triggered plan is inserted.

**Comment by Rkareko** [comment]
@madrinekariuki 

Case triggered plans:
1.
ff975b91-68e7-4550-8f61-a3100a6cb959

The above plan does not have any `case_confirmation` tasks that is why the alert is displayed i.e

```
   select count(*), code from core.task_metadata where plan_identifier = 'ff975b91-68e7-4550-8f61-a3100a6cb959' group by 2;
 count |         code         
-------+----------------------
    73 | RACD Register Family
     7 | Mosquito Collection
     1 | BCC
    10 | Larval Dipping
    29 | Bednet Distribution
   135 | Blood Screening
```
More investigations will be required to determine why the `case_confirmation` tasks were not generated. The alert is correct

**Comment by Rkareko** [comment]
@madrinekariuki 

Case triggered plans:
2.
`d3f20435-6427-44b2-b012-e2b662688435`

No tasks were generated for this plan i.e

```
select count(*), code from core.task_metadata where plan_identifier = 'd3f20435-6427-44b2-b012-e2b662688435' group by 2;
 count | code 
-------+------
(0 rows)
```
The jurisdiction this plan is assigned to has only 1 structure which is `Residential` i.e

```
select count* from core.structure_metadata where parent_id = 'b58053e8-84b6-4a0d-9793-29f2356a6735';
  id   | structure_id |              geojson_id              |         type          |              parent_id               |                 uuid                 |     status     | server_version | name |        date_created        |       date_edited       
-------+--------------+--------------------------------------+-----------------------+--------------------------------------+--------------------------------------+----------------+----------------+------+----------------------------+-------------------------
 59027 |        59027 | 05a3154a-74fd-441e-8297-d1fe2dfbbe4b | Residential Structure | b58053e8-84b6-4a0d-9793-29f2356a6735 | d2915b0e-7a85-43d2-8f3e-557304096025 | PENDING_REVIEW |  1607066335008 |      | 2021-10-28 07:54:06.404174 | 2021-10-28 07:54:06.406
```
This means that only tasks linked to Residential structures can be generated. `Larval Dipping` and `Mosquito Collection` tasks cannot be generated for this plan thus no alerts for them would be generated.

The existing structure has a family registered with a single resident. Since a family has already been registered we don't expect a family registration task to be generated. Only a blood screening task should be generated 

```
select first_name, last_name, residence, birth_date, client_type from core.client_metadata where residence in (select geojson_id from core.structure_metadata where parent_id = 'b58053e8-84b6-4a0d-9793-29f2356a6735' and type = 'Residential Structure') ;
 first_name | last_name |              residence               | birth_date | client_type 
------------+-----------+--------------------------------------+------------+-------------
 Test       | Family    | 05a3154a-74fd-441e-8297-d1fe2dfbbe4b | 1970-01-01 | Family
 Test       | T         | 05a3154a-74fd-441e-8297-d1fe2dfbbe4b | 1996-10-28 | 


```

**Comment by Rkareko** [comment]
Case triggered plans:
3.
`4bac463a-e38c-4cc0-9c03-3754a388d1f4`

No case confirmation task was generated as seen below 

```
select count(*), code from core.task_metadata where plan_identifier = '4bac463a-e38c-4cc0-9c03-3754a388d1f4' group by 2;
 count |        code         
-------+---------------------
     1 | Bednet Distribution
     1 | Blood Screening
```

More investigations will be required to determine why the case_confirmation tasks were not generated. The alert is correct

**Comment by Rkareko** [comment]
@madrinekariuki @samkanga generation of `Case Confirmation` tasks is failing because the `Case Confirmation` action in the plans has the wrong `subjectCodableConcept` an example is the [plan with id `4bac463a-e38c-4cc0-9c03-3754a388d1f4`](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/4bac463a-e38c-4cc0-9c03-3754a388d1f4)

The current value is `Jurisdiction` i.e 
```
      "subjectCodableConcept": {
        "text": "Jurisdiction"
      },
```

The correct value should be `QuestionnaireResponse` i.e

```
"subjectCodableConcept": {
          "text": "QuestionnaireResponse"
        }
```

The fix for this is updating the plan templates [1](https://reveal-th-preview.smartregister.org/opensrp/rest/templates/1) and [2](https://reveal-th-preview.smartregister.org/opensrp/rest/templates/2) with the correct `subjectCodableConcept`

**Comment by samkanga** [comment]
@Rkareko on the templates 1 and 2 shared above, I can only see the BCC section with the `subjectCodableConcept` showing `"text": "Jurisdiction"`. The case confirmation `subjectCodableConcept` on the templates reads "text": "QuestionnaireResponse". However for the shared plan reads `"text": "Jurisdiction"`. Do you know why that may be different? cc: @ciremusyoka

**Comment by Rkareko** [comment]
@samkanga I have already updated the templates with the correct `subjectCodableConcept` values for the `case confirmation` actions

**Comment by madrinekariuki** [comment]
@samkanga @Rkareko  
please find below my findings on this after the fixes.

We still have an issue with some tasks not being picked. i.e Register Family and Bednet Distribution. see below in no. `1` and `3 `

**Created plans** 
Case triggered plan
A1 - บือลาพอ (6304060703) - QA tasks test 1 - 2022-01-12 - Site   cc38dac9-3b9e-43e2-960b-a99620ecd93f
A2 - ธรรมชาติ(ล่าง) (2305070601) - QA tasks test 1 - 2022-01-12 - Source 49ddcad0-46e9-45dc-adf3-dd5745214bc3

A1 - บือลาพอ (6304060703) - QA tasks test 2 - 2022-01-12 - Site  654d0bbd-a3b0-4ca7-95f2-b71d7b83e5f2
A2 - ธรรมชาติ(ล่าง) (2305070601) - QA tasks test 2 - 2022-01-12 - Source    bf501e10-9de1-4c3a-b8a5-d5361f3b8f38

routine plan
N/A Thailand test site BVBD 1 2022-01-12 Ny 1  dadb0d52-31e9-51a7-9792-03619dbb0e04


**Test findings**
**1. Case triggered site plan**
`cc38dac9-3b9e-43e2-960b-a99620ecd93f`
removed
```
RACD register family
BS
```
observation
- endpoint shows the missing tasks are` Blood Screening`. Why was Register Family Omitted?
- on the reveal logs channel alert correctly shows  Blood screening alert.

screenshots:
![image](https://user-images.githubusercontent.com/84722169/149128205-a9be8096-610d-4b63-9721-86dd3f48d69e.png)


**2.Source plan**
`49ddcad0-46e9-45dc-adf3-dd5745214bc3`
No tasks removed

observation
No alert generated  for this one.

**3. Site plan** 
`654d0bbd-a3b0-4ca7-95f2-b71d7b83e5f2`
removed all tasks
  Case conf
  Register Family
  Blood Screening
  BCC
  Bednet distribution
  larval dipping
  mosquito collection

observation
- The endpoint has only picked 5 missing tasks i.e Blood screening, BCC, Case confirmation,Larval dipping, Mosquito collection.  `Register Family` and `Bednet distribution` were not picked.
- Alert also shows the above missing tasks. Why was register family and bednet distribution omitted?

screenshot.
![image](https://user-images.githubusercontent.com/84722169/149125609-c3a82ab7-8c6b-4cb2-b275-361a80ae236c.png)



**4.   Source plan**
`  bf501e10-9de1-4c3a-b8a5-d5361f3b8f38`
  removed
  case confirmation

  observation
- The endpoint correctly  shows missing Case confirmation task.
- The alert was also successfully sent to the reveal logs channel

screenshot
![image](https://user-images.githubusercontent.com/84722169/149126283-48f9896a-b362-4a67-930a-14b36c8ef08f.png).


**5. routine plan**
  `dadb0d52-31e9-51a7-9792-03619dbb0e04`
removed
BS
BCC

observation
- Endpoint correctly shows missing Blood Screening and BCC tasks
- Reveal logs channe correctly shows missing Blood Screening and BCC alert.

screenshot
![image](https://user-images.githubusercontent.com/84722169/149126921-5cd8b587-04ce-4e8a-9b49-ecec05820168.png)

**Comment by madrinekariuki** [comment]
@Rkareko @samkanga 
we still have an issue: 

**Failing test cases:**
- Verify no alert is generated for a plan without missing tasks
- Verify that correct alerts are generated for the correct missing task. 

Noted issues on below `3` plans (one is a `source plan`, 2 are` routine plans`).

**created plans** 
`18b50c24-3eef-490c-a836-86b20ebb4974 `   QA tasks test 1 - 2022-01-19 - Site
`a15a7b47-9dcd-4117-b9d6-252e28ab48aa`   QA tasks test 1 - 2022-01-19 - Source
`073624eb-844b-498d-934f-117121266d79`   QA tasks test 2 - 2022-01-19 - Site
`fe2ccaac-24d6-4792-8033-3e5ce944c18c `  QA tasks test 2 - 2022-01-19 - Source
`88211af9-b483-5cd1-ba19-6861e88552da `  N/A Thailand test site BVBD 1 2022-01-19 routine
`cdfce91e-e9dc-5c3c-b2f3-4a4c9c5ea431 `  N/A Thailand test site BVBD 2 2022-01-19 routine 2
`78a4e237-8491-5f5a-8277-b5c18da3c7cd `  N/A Thailand test site BVBD 3 2022-01-19 routine 3



**TESTS**
1. site plan
`18b50c24-3eef-490c-a836-86b20ebb4974  `
removed
register family
blood screening
bednet distribution

observation.
-API endpoint picked the 3 missing tasks
-On reveal logs channel alerts were generated for the 3 missing tasks

2. Source plan
a15a7b47-9dcd-4117-b9d6-252e28ab48aa
removed
case confirmation
register family

observation:
- API endpoint picked the 2 missing tasks
- On reveal logs channel alerts were generated for the 2 missing tasks

3. site plan
073624eb-844b-498d-934f-117121266d79
removed ALL tasks
case confirmation
register family
blood screening
BCC
bednet distribution
larval dipping
mosquito collection

observation
- API endpoint picked the 7 missing tasks
- On reveal logs channel alerts were generated for the 7 missing tasks

4. source plan
fe2ccaac-24d6-4792-8033-3e5ce944c18c     
NO tasks removed

observation
- register family task had an alert generated. despite it being available on the payload.

5. routine plan
88211af9-b483-5cd1-ba19-6861e88552da      
removed
 register family
 bednet distribution

 observation
 - API endpoint picked the 2 missing tasks
- On reveal logs channel alerts were generated for the 2 missing tasks


6. routine plan
cdfce91e-e9dc-5c3c-b2f3-4a4c9c5ea431
No tasks removed

observation
- API shows 2 missing tasks
- Alerts generated for bednet distribution and Register family


7. routine plan
78a4e237-8491-5f5a-8277-b5c18da3c7cd
removed 
Blood screening

observation
- API shows 3 missing tasks
- Alerts generated for blood screening, bednet distribution and Register family

**Comment by madrinekariuki** [comment]
@Rkareko @samkanga 
please note the current issue below
 **failed scenario**
-  Verify that correct alerts are generated for the correct missing task.

**expected outcome**
- We should have the correct  missing task alerts generated for the correct missing alert.

plans used for the scenarios noted above:
**1**. `9310946e-e04f-4b22-8dfd-df25775376a8`
removed 
```
register family
bednet distribution
```

observation
- alert generated for blood screening instead of register family and bednet distribution

**2**.`9bf386cd-e3e2-5656-9a43-2c1d8660417f`
removed
` blood screening`

observation
- picked by the api. (Blood screening, register family and bednet distribution)
- alerts generated for the 3 as well. (Blood screening, register family and bednet distribution)

**Comment by Rkareko** [comment]
@madrinekariuki @samkanga concerning plans with identifiers `dc5b5fa4-5c28-5d0c-a08f-8352093f8ded` and `ce5948bc-23dc-565a-8c4e-c3568a232455` . The jurisdictions they are linked to do not have any structures. You can use the [this](https://reveal-th-preview.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=false&properties_filter=parentId:70ad234e-4e15-4e02-a8fc-6722fe87166f) and [this](https://reveal-th-preview.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=false&properties_filter=parentId:db7685f6-b722-49e4-9748-dfba258def84) API endpoints to verify. This is why we don't expect any `register Family`, `Bednet distribution`  tasks to have been generated

**Comment by madrinekariuki** [comment]
@Rkareko @samkanga 

Above scenarios are still failing. 
**failed scenarios**
- Verify that alerts are generated for all missing tasks
- Verify that Alerts are generated correctly for all the tasks that are missing.

As noted from the plans below, we still seem to have an issue around `Bednet distribution `and `Register Family`

**1.**
`e895661d-e87d-557c-a319-f2331e29226f`
removed 
Blood Screening

observation
Has blood screening and Bednet distribution tasks missing.

**2.**
`c339b7b9-9a9e-4743-8d89-63b41e504ed5`
removed all tasks

observation.
register Family was not generated all the rest were generated.

**3.**
`d319bfc8-9284-46f2-a1f8-80d7ac79d754`
removed.
case confirmation
register family

observation
only case confirmation was generated register family was not generated.

**Comment by madrinekariuki** [comment]
@samkanga @Rkareko 

Re-tests have been done and have passed QA. 

Tested test cases/scenarios are:

- Verify that alerts are generated for all missing tasks on a case triggered plan
- Verify that alerts are generated for all missing tasks on a routine plan
- Verify that no alerts are generated if no tasks is  missing
- Verify that if all tasks are removed from a plan, Alerts are generated for ALL the missing tasks.
- Verify that missing tasks  are picked by the api endpoint
- Verify that alerts are generated correctly for all the tasks that are missing.
- Verify that the API endpoint displays the missing alerts correctly
- Verify that the alerts are sent to the reveal logs channel.



Plan used:
**1.**
`994fc981-db48-5b08-98aa-3e28c65c513d`
removed all tasks

observation
all missing 3 tasks have been picked by the api and alerts sent to the reveal logs alert channel

**2.**
`be7e7e70-896b-5813-9347-48bf6c1bb5ed`
removed
Register Family
BCC
Bednet

observation
all missing 3 tasks have been picked by the api and alerts sent to the reveal logs alert channel

**3.**
b10d65f8-9999-4d6f-a206-972594d37e8d
removed all tasks.

observation
all missing tasks have been picked by the api and alerts sent to the reveal logs alert channel

**4.**
`78e7322e-1e3a-4eb1-a823-3859fa993ff2`
removed
case confirmation
register family
bednet

observation
all missing 3 tasks have been picked by the api and alerts sent to the reveal logs alert channel
