### ISSUE TITLE
Missing BCC task on Thai Local instance. 

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-server-web#1050]
It has been noted that BCC Focus Task is missing on the Thai local instance.
This has been noted on case triggered plans and also routine plans.

plan id
62e446e8-0297-42ad-a79c-5a10f3982f5e  Case triggered plan
9209b9ea-3d7c-450a-9834-6359ed6d464c Case triggered plan
ef795ee2-44d4-5716-a4e6-0a6a2e2b152a routine plan

steps:

- create a plan
- activate the plan and confirm your team has been assigned to the plan
- login to the apk (used v5.3.29 Thai-en)
- sync data and opn your plan
- observe on the List view how the plan is missing BCC tasks.

screenshots:
![image](https://user-images.githubusercontent.com/84722169/149086713-6e303d51-1544-4986-824e-46a6013e514e.png)

**Comment by madrinekariuki** [comment]
@Rkareko 
As requested please find below Failing test cases for this issue
- Verify that routine plans have BCC tasks generated.
- Verify that Case triggered plans have BCC tasks generated.
- Verify that one is able to complete a BCC tasks on both Routine and Case triggered plans (not tested since we o not have a BCC task)

**Comment by Rkareko** [comment]
@madrinekariuki @samkanga Task generation is failing due to the reason stated [here](https://github.com/opensrp/opensrp-server-web/issues/1051#issuecomment-1012733486) 

@madrinekariuki could you repeat this test on another test location

**Comment by madrinekariuki** [comment]
retest has been done and comment shared [here](https://github.com/opensrp/opensrp-server-web/issues/1051#issuecomment-1012813482)
