### ISSUE TITLE
Integrate Test Containers for integration Test.

### ISSUE THREAD

**Issue by bennsimon** [opensrp/opensrp-server-web#1087]
### Benefits of [Test containers](https://www.testcontainers.org/) 
- No need to setup and configure before-hand external services opensrp uses e.g postgres, rabbitmq, redis and any other when running integration tests locally or on a CI. 

TestContainers create throwaway docker containers for these services, meaning one gets on going faster when writing/running integration tests without necessarily having to create environment for the tests.

**Comment by dubdabasoduba** [comment]
@bennsimon To follow up on the PR status and close the ticket.
