### ISSUE TITLE
proxy to openMrs to get userId when creating a practitioner

### ISSUE THREAD

**Issue by p-netm** [OpenSRP/opensrp-server-web#133]
Need an userId from openMRS , so as to link the the practitioner to an openMRS user.
    Will probably need a proxy on the opensrp server that helps get this data from openMRS.

Reference : onaio/reveal-frontend#458

**Comment by githengi** [comment]
@cKellyDesign @moshthepitt @mberg Do we have any mock-ups for this.

I am assuming this will be be needed by a look up widget or drop down for selecting the OpenMRS user.

**Comment by moshthepitt** [comment]
![users](https://user-images.githubusercontent.com/372073/66146767-13f4f380-e616-11e9-896a-03423ff3aafd.png)

@githengi ^^
