### ISSUE TITLE
Ensure event serverVersions are unique

### ISSUE THREAD

**Issue by Wambere** [OpenSRP/opensrp-server-web#135]
There are multiple events with the same serverVersion. 
For example events with id `5b33a8d2-46af-486f-990c-9a10f2aafabd` , `bd6ff3ce-ace4-4529-b35c-9723300e27ea` and `337ae7de-2313-48fd-9e44-11cec4320851` all have the serverVersion `1569436074641`

Canopy pulls events from openSRP based on serverVersion. So for example if one record is pulled in with serverVersion `1569436074641`, the next pull will get events where serverVersion is greater than what we already have. This means that we are not getting all the events since some are lost/ignored because of duplicates. 

We need to fix this to ensure that we are retrieving all events from openSRP

**Comment by ukanga** [comment]
Is the server version supposed to be unique? If not, how else can we get all the information matching a particular server version?
