### ISSUE TITLE
Add a default Error Handler

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#245]
- [ ] Add a default error handler that will be returned if any uncaught exceptions occur in the server.

- [ ] The returned content should be a generic error message and  HTTP 5XX status code

**Comment by craigappl** [comment]
@githengi , 

1. Please write the text of a generic error message.
2. Does this message need to support multiple languages?

**Comment by githengi** [comment]
The generic error message should be "The server encountered an error processing the request."

@craigappl not sure if supporting multiple languages is a priority. This can be addressed for the whole of the server ApIs

**Comment by githengi** [comment]
Remove try blocks in the APIs that have a generic catch like the one below so that the global error handler is used 

```
catch (Exception e) {
	  logger.error(e.getMessage());
	  return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR)
}
```
