### ISSUE TITLE
Update the server side validator to show reference errors during upload 

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#345]
- [x] The server side validation should catch any file reference errors during upload. 

Do you guys think we can update native forms to have an easier way of knowing what files are references instead of having to traverse the form?

- The question above mostly applies for sub forms & rules files

- JMAG appends the property file name on the property `"properties_file_name"` e.g `"properties_file_name": "anc_close"`

**Comment by ekigamba** [comment]
LOE = 6 hours
