### ISSUE TITLE
Create the JSON Validator tables on OpenSRP

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#360]
- [ ] Table 1 will be named client_form_validator. This will have the following columns

`id` - Auto incrementing unique identifier - `integer`
`json` - Holds the actual validator json - `jsonb`
`created_at` - holds the time when the row was save in the database - `timestamp`

- [ ] Table 2 will be named client_form_validatior_metadata. This will have the following columns

`id` - Auto incrementing unique identifier - `integer`
`client_form_validator_id` - Foregin key for the table client_form_validator - `integer`
`client_form_identifier` - holds the identifier of the client form it should validate - `varchar`
`version` - holds the version of the JSON validator - `varchar`
`created_at` - holds the time when the row was save in the database - `timestamp`

- [ ] Write migrations for these tables creation

**Comment by cafootitt** [comment]
No longer needed.
