### ISSUE TITLE
Create a JSON form validation API endpoint

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#361]
- [ ] The URL (Uniform Resource Locator) for the said endpoint will be `/rest/client-form-validator`

- [ ] GET method should achieve the following. 

Gets all the form validators - `/`
Gets form validators via  identifier - `/{id}`
Gets for validators via client form identifier - `?client_form_identifier={form_identifier}`

- [ ] POST, PUT, PATCH methods payload should have the following.

The validator JSON  - e.g this sample 
Validator version - e.g 0.0.1
Client form identifier - e.g anc_regisration
The validator id - e.g 1

**Comment by cafootitt** [comment]
No longer needed.
