### ISSUE TITLE
Thoughts on loction/plan/{planidentifier}

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-server-web#435]
## Summary

The web UI is trying to use the plan jurisdictions hierarchy API endpoint and encountering some problems.  This issue is meant to provide more context on how the web UI is using this endpoint, and the problems encountered with the hopes of working towards a solution.

In summary, we should consider the following:

- [ ] Let's improve the performance of this endpoint
- [ ] Let's review access control on this page
     - [ ] Do we need access control to view plan jurisdictions?
     - [ ] If a user is able to create and modify a plan, then that user should be able to view a plan's jurisdictions hierarchy
- [ ] Let us ensure known 500 exceptions are handled

## Intended use-case

In the web UI, once a plan is created and activated an admin user then needs to assign teams to all of the plan's jurisdictions.  We therefore need this endpoint to return the plan's jurisdictions hierarchy so that it is possible to make team assignments on the plan's jurisdictions at any level of the hierarchy. 

### 1. Performance

We have encountered situations where the endpoint takes up to five minutes to load even fairly small plans.  For example, his fairly small plan (only 7 jurisdictions) takes 4.4 minutes to load before it returns a 500 level error: https://reveal-stage.smartregister.org/opensrp/rest/location/getHierarchy/plan/6166163a-c73e-5720-acc9-cb097ca35ab6?return_structure_count=false

Note that return_structure_count === false

### 2. Access control

From conversations with @githengi and @Rkareko it seems that when you try and access this endpoint, the server evaluates whether the user belongs to any organizations that have been assigned to jurisdictions in the plan.  I think that this presents a significant problem.  i.e.

- From the intended use-case of the web app, we are trying to make team assignment to all of a plan's jurisdictions.  It defeats the purpose of team assignment if the user cannot get access to all of the plan's jurisdictions.  How can you assign teams to plan jurisdictions if you cannot access all of the jurisdictions?
- On Reveal stage the web user is `superset-user`.  This user is able to create plans and assign plan jurisdictions and view them in full.  Why would this same user then be restricted from accessing a plan's jurisdiction hierarchy?
- Do we consider the plan's jurisdictions as sensitive information that needs access control limitations?  Why?  This same web user can load all jurisdictions, and jurisdiction hierarchies.  It does not seem consistent that they would then not be able to load plan jurisdictions (of plans that the same user has full ability to create and modify).
- I think checking for access control that we may not lead contributes to the poor performance of this endpoint. 

### 3. Un-handled exceptions

It seems that if a user cannot access plan jurisdictions, the system encounters a HTTP 500 exception.  I think we should use a 4xx HTTP status instead of an exception.

## Related issues

- https://github.com/OpenSRP/opensrp-server-web/issues/432
- https://github.com/OpenSRP/opensrp-server-web/issues/434

**Comment by moshthepitt** [comment]
This is meant to support the web UI plan team assignment page e.g. https://web.reveal-stage.smartregister.org/assign

**Comment by Rkareko** [comment]
1. **Performance**  
We are working on optimizing the query used to build the location hierarchy.

2.  **Access control** 
The initial thinking was that a user making the API call would only get a location hierarchy if they have access to the plan.
The `superset-user` used by the web UI would be given super-user privileges that allow for the access of all plans and plan hierarchies.
In the meantime we have removed the check for whether the user has access to the plan. This allows `superset-user` the ability to fetch all location hierarchies.

3.  **Un-handled exceptions** 
The API endpoint will be updated to return a 4xx HTTP status instead of an exception.

**Comment by moshthepitt** [comment]
@Rkareko it seems that the performance problems of this are back to haunt us e.g. https://reveal-stage.smartregister.org/opensrp/rest/location/hierarchy/plan/14763f37-4afa-5a72-894e-fead31738a25?return_structure_count=false
