### ISSUE TITLE
Create an API that returns Users from Keycloak

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#458]
- [x] Create an API that returns Users from Keycloak for use on Web UI

- [x] The current API returns users from OpenMRS

**Comment by githengi** [comment]
@moshthepitt the payload will be changing that we get from keycloak for users to as shown in sample below
```
[
    {
        "id": "5d2db33e-c763-457b-94be-d62abe70ad66",
        "createdTimestamp": 1595352823770,
        "username": "apdemo1",
        "enabled": true,
        "totp": false,
        "emailVerified": false,
        "firstName": "Abimbola",
        "lastName": "Phillips",
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": false,
            "manage": true
        }
    },
    {
        "id": "e685110d-a53a-460d-9abc-ec157382a677",
        "createdTimestamp": 1595353079984,
        "username": "bademo1",
        "enabled": true,
        "totp": false,
        "emailVerified": false,
        "firstName": "Bashir",
        "lastName": "Ahmad",
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": false,
            "manage": true
        }
    }
]
```

Can I send that back instead of formatting it to look like the OpenMRS one. 

We can add a new endpoint for keycloak so that the older is deprecated with time. Also its now possible to search with Keycloak API is that something that can be added as an optional search param for the proxy API.

Also keycloak exposes an API for getting users count, This would then be used to to make the API calls to the above.

**Comment by moshthepitt** [comment]
@githengi looks exciting!  Yes I think you don't have to format it to look like OpenMRS (yuck!).

Hpwever, I am really interested in the `access` field in the payload.  Seems like we could use this for role-based access control in the web UI.  So I have questions:

- Do you think we could add more items here that can allow us to check if a user is allowed to do things like create plans, assign teams, create team etc?  What would that look like?
- What do the things that are here right now like view, impersonate, etc mean?

**Comment by moshthepitt** [comment]
@githengi also maybe we need to change the user-details endpoint to match this structure

**Comment by githengi** [comment]
@moshthepitt 
We use user Details endpoint to return roles that a user has access to. This can then be used to enforce role based access. The user details has a list of roles on the `roles` key.

View and impersonate and all keys user `access` contains the details of the user access on keycloak. These would be different from application permissions which would be the roles a user is assigned. 

Getting the list of users we are invoking keycloak User API, this does not allow one to get effective roles per user. Roles on the user details we extract from the access token .

We can harmonize the the 2 endpoints to return similar keys for the data but will not be possible to return same data for both
