### ISSUE TITLE
Failure to authenticate API via new OAuth mechanisms results in 302 Found redirect and status 200

### ISSUE THREAD

**Issue by gstuder-ona** [OpenSRP/opensrp-server-web#465]
When using the OpenSRP APIs protected by keycloak (EDIT: only tested on reveal-stage, maybe specific to that server), a failure to authenticate doesn't result in a 403 status but instead a redirect to a human-readable login page.  This breaks API consumers in a hard-to-fix way, since the redirect (302 found) gives no indication that an authentication error happened in the process and so the html is parsed as json.  For now, it seems we have to hardcode checks for the content type returned.

Adding an "Accept: application/json" header seems to be ignored, and text/html is still returned, but maybe there's another way to manage this.  Is there a header that will turn the redirects off?

**Comment by gstuder-ona** [comment]
@ukanga flagging this to you as a high priority for the canopy team to either get educated on, fix, or find a workaround for

**Comment by githengi** [comment]
@gstuder-ona add header `X-Requested-With` with value `XMLHttpRequest`

**Comment by gstuder-ona** [comment]
@githengi awesome thx.
