### ISSUE TITLE
Improve performance of rest/location/findByProperties

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-server-web#469]
It now takes 1.6 minutes to load: `https://reveal-stage.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=true&return_geometry=false&properties_filter=status%3AActive%2CgeographicLevel%3A0` - is it possible to improve the performance of this?

**Comment by moshthepitt** [comment]
It seems that this problem is back to haunt us e.g. https://reveal-stage.smartregister.org/opensrp/rest/location/hierarchy/plan/14763f37-4afa-5a72-894e-fead31738a25?return_structure_count=false

**Comment by Naima-Bashir** [comment]
okay, so it takes about 2 minutes for the countries to load. 
Which is part of this fix: https://github.com/OpenSRP/opensrp-server-web/issues/469
I will close this issue and retest when 469 is done.
cc @moshthepitt @ciremusyoka

**Comment by githengi** [comment]
query now taking less than 2 seconds after indexing location properties json
