### ISSUE TITLE
Implement Supply Catalog API

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#506]
- [ ] Implement Supply Catalog API for allowing adding, editing, viewing and searching of supply catalog

Depends on https://github.com/OpenSRP/opensrp-server-core/issues/306

**Comment by rehammuzzamil** [comment]
Here are the implementation details:
**POST**  - To create a Product Catalogue, I will be using contentType as **multipart/form-data**, an image (optional) and actual payload can be sent together in a request, for this purpose @RequestPart is being used. For uploading of the image, existing code is used of MultimediaService to save the image file against caseId equals to the uniqueId of productCatalog, and providerId equals to the userName, and for the file category "catalog_image" is used. 
**GET**  - Only the data response is being returned and the image file can be downloaded through the already existing end-point of Multimedia Controller` /multimedia/media/{entity-id}`

Please correct me if there is anything wrong @githengi . Thanks.
