### ISSUE TITLE
Implement the Login Page Look and Feel

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#52]
Implement the Login Page Look and Feel to look more like Reveal theme or ONA but blue OpenSRP theme.

The current page was just to support a MVP for login.

@rowo maybe you can design the mock-ups for OpenSRP login page

**Comment by rowo** [comment]
@githengi What is this for? The Reveal web?

**Comment by githengi** [comment]
Its an OpenSRP login page that will be displayed in Reveal web and Canopy so that a user can be able to login in

**Comment by rowo** [comment]
@craigappl @githengi Is this the log in screen? Are there any other requirements here or will it be functionally the same?

<img width="1138" alt="Screen Shot 2019-06-19 at 3 13 58 PM" src="https://user-images.githubusercontent.com/1584163/59793581-e7a2aa80-92a4-11e9-9a54-63bf296f6781.png">

Also — I'm not sure if our goal is to match up Reveal and OpenSRP branding-wise. @mberg do you have any thoughts on this?

**Comment by githengi** [comment]
The login page is the one opened after you click on the OpenSRP button on the above screen.

**Comment by moshthepitt** [comment]
#### This is the login page:

![OpenSRP Authorization Server login](https://user-images.githubusercontent.com/372073/59833115-0f9a1880-934e-11e9-882a-ca3af1adc044.png)

#### This is the oAuth approval page that comes right after:

![oauth approval](https://user-images.githubusercontent.com/372073/59833137-1fb1f800-934e-11e9-8c42-06f8c24e4340.png)

**Comment by rowo** [comment]
Similar to the rest of Reveal, I think we should match up closely to Bootstrap out of the box. Here's an example: https://getbootstrap.com/docs/4.0/examples/sign-in/. The logo would be updated with Reveal's. For the approval step, I think you can keep the logo in the same place and replace the username/pass inputs with the buttons (with Authorize as bootstrap green).

For OpenSRP, Tobi is working on a separate look and feel. I don't think they should match up right now.
