### ISSUE TITLE
[THAI]- When sorting by last modified, the date and plan names change order but the dates and other columns do not RVL-1134

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-server-web#521]
Login to web preview:
https://web.reveal-th-preview.smartregister.org/plans/list
Click on the sorting by last modified or status. Observe how the status column doesn't change
Observe how when sorting by last modified date the plan names change order but the dates and other columns do not
![image](https://user-images.githubusercontent.com/61143692/92382279-047b0600-f115-11ea-8f36-50e1c66562bb.png)

**Comment by samkanga** [comment]
I will close this issue and recreate it on the canopy repo
