### ISSUE TITLE
Jurisdiction Sync sync use location Ids instead of location names

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#527]
- [x] Jurisdiction Sync sync use location Ids instead of location names

- [x] Names were used when location hierarchy depended on OpenMRS locations. 

- [x] OpenMRS locations does not allow duplicate location names, while OpenSRP locations allow duplicates.

- [x] Save Jurisdiction Ids when on the authentication payload so that android client can send locationIds instead of names

related to https://github.com/OpenSRP/opensrp-client-reveal/issues/999

**Comment by craigappl** [comment]
Make sure that this is available for all location sync across the OpenSRP system so we aren't mixing sync processes in the future. Ideally, legacy apps would use the existing mechanism and would switch over to jurisdiction id sync when OpenMRS is removed.
