### ISSUE TITLE
Inactive structures/jurisdictions/locations do not appear in REST get-by-id or getAll queries

### ISSUE THREAD

**Issue by gstuder-ona** [OpenSRP/opensrp-server-web#537]
When trying to ETL data from OpenSRP, inactive locations do not appear in API results (they look the same as deleted locations) and so the newly-inactive status can't be sync'd to the ETL database.  Also, there's no distinction in the API results between inactive and missing locations, making tracking down data issues require direct access to the OpenSRP database.

One backward-compatible solution would be to add a flag 'includeInactive=true' that would include inactive locations in the API results.  Alternately, it's backward-compatible to return inactive locations by id and ETL processes have been expecting inactive locations already via getAll, so maybe just including inactive locations in these results would be the better solution.

**Comment by githengi** [comment]
Project: Reveal

**Comment by rehammuzzamil** [comment]
As per my investigation, the following end-points will be impacted :  

- `/rest/location/getAll`
- `/rest/location/{id}`

As per the current flow, all structures are returned in response without any filter of status for both get by id and get all structures, therefore, the queries for structurerepo won't be impacted. Wrt both the APIs a new boolean param `includeInactive` will be added with a default value of false.
cc : @githengi
