### ISSUE TITLE
Implement CSV import on the Stock API

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#557]
- [ ] Implement CSV import on the Stock API that will be used to import Inventory items in this [mockup](https://marvelapp.com/prototype/6agej0e/screen/73081456) 

- [ ] The import should have validation rules and should only import if all records are valid.
-- Service point ID is a valid ID of a service point in the georegistry, required
-- Product ID is a valid ID of a product in the product catalogue, required
-- Quantity is a whole number equal to or greater than one, optional
-- Delivery date is a valid date in the past (i.e. cannot be a future date), required
-- Unicef section is one of the possible Unicef sections to choose from, required
-- Serial number is free text and required if product is an attractive item
-- Donor is one of the possible Unicef donors to choose from, optional
-- PO number is a whole number, required

- [ ] The import should return a list validation errors for any line which have any validation errors and show the row number in the CSV that contains the error.

service_point_name | service_point_id* | product_name | product_id* | quantity* | delivery_date* | unicef_section* | serial_number* | donor* | po_number*
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Alarobia Ambatomanga CSB | 89879388 | Midwifery Kit | S990222 | 1 | 04/08/2020 | Health |   | Gates | 897
Alarobia Ambatomanga CSB | 89879388 | Motorcycle | S2873493 | 1 | 05/01/2015 | Health | 198273972888 | GAVI | 898
Alarobia Ambatomanga CSB | 89879388 | Amoxicillin | S2729878 | 50 | 05/05/2020 | Health |   | GAVI | 897
EPP Tsaratanana | 77787328 | Motorcycle | S2873493 | 1 | 10/01/2015 | Education | 19783397288 | UNICEF | 897
EPP Tsaratanana | 77787328 | Scientific Suitcase | S2783472 | 100 | 30/12/2019 | Education | 287394872 | UNICEF | 897

`* Items marked with an asterisk are what would need to be used/stored/parsed.
** Service point name and product name can be ignored on upload, as we’re using the IDs instead.

**Comment by rehammuzzamil** [comment]
Here are the implementation details: As per my understanding of the business, the user will upload a **CSV** file, having columns mentioned in the issue. Based on the CSV data, inventory data will be persisted in the **Stock** table after successfully passing all the validation rules. If any row fails to pass a validation rule, that row's data won't be persisted and will be stored in a FailedRecordSummary object. Once, all the rows are processed, csvBulkImportDataSummary is returned in a CSV file which would contain information about the failed row number along with the reason for their failure. 
cc: @cafootitt @githengi

**Comment by rehammuzzamil** [comment]
@cafootitt Do we have a list of possible UNICEF sections and donors?

**Comment by cafootitt** [comment]
@rehammuzzamil 

Here are the UNICEF sections:

Health
WASH
Nutrition
Education
Child Protection
Social Policy
C4D
DRR


As for donors, we have the list, but I'm just confirming something with the client first before sharing. Will revert back as soon as I hear from them.

**Comment by cafootitt** [comment]
@rehammuzzamil here is the list of possible donors


ADB
NatCom Belgium
BMGF
Govt of Canada
NatCom Canada
NatCom Denmark
ECW
End Violence Fund
ECHO
EC
NatCom Finland
Govt of France
NatCom France
GAVI
NatCom Germany
Govt of Germany
NatCom Iceland
NatCom Italy
Govt of Japan
NatCom Japan
NatCom Luxembourg
Monaco
NatCom Netherlands
Govt of Norway
NatCom Norway
Nutrition Intl
NatCom Poland
Govt of Korea
NatCom Spain
NatCom Sweden
NatCom Switzerland
Govt of UK
NatCom UK
NatCom USA
OFDA
CDC
USAID
USAID FFP
World Bank

**Comment by rehammuzzamil** [comment]
These files contain payload to register donors and sections in a Settings Configuration using **/rest/settings/sync** endpoint.
As per discussion with @githengi, these values should be added after the deployment.
FYI @cafootitt 

[Donors.txt](https://github.com/OpenSRP/opensrp-server-web/files/5446317/Donors.txt)
[Unicef Sections.txt](https://github.com/OpenSRP/opensrp-server-web/files/5446318/Unicef.Sections.txt)

**Comment by cafootitt** [comment]
Just seeing the comment above, so I'm noting here that this was implemented as the "all or nothing" upload approach. I.e. no data is persisted until the entire csv uploads without errors.

**Comment by rehammuzzamil** [comment]
@p-netm you can find the validations of import CSV in this issue that will be done on the server-side.
