### ISSUE TITLE
Extend Stock API 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#558]
Extend Stock API to provide the below functionality

- [ ]  Adding 1 item on the root URL using POST

- [ ] Updating 1 item on the root URL/{identifier} using PUT

- [ ] Delete 1 item on the root URL/{identifier} using DELETE

- [ ] Deletion should be a soft delete i.e using a date_deleted to filter deleted records

**Comment by githengi** [comment]
When saving inventory populate the stock entity with the below

- [ ] identifier - Catalog unique identifier
- [ ] providerid- Logged in username
- [ ] value - Quantity
- [ ] transaction_type- Inventory
- [ ] locationId - Service Point Id
- [ ] [Newly added Fields](https://github.com/OpenSRP/opensrp-server-core/issues/333) should be be populated as they are

Validation rules
- Quantity  >=1
@cafootitt please add any validation rules that may be required f

**Comment by rehammuzzamil** [comment]
Here are the implementation details, we will be using the existing entity of **Stock** for Inventory items. For this purpose, we need to add new fields in the Stock entity as mentioned in [Issue # 333](https://github.com/OpenSRP/opensrp-server-core/issues/333). 
The API for creating, update and delete will be exposed on StockResource which would create Stock from the **Inventory** object. The fields of the Inventory object and mapping are defined in this document in Tabular form:
https://docs.google.com/document/d/1Q7c8oKuOdRmACcHfZvR_rEuTyuYQRYQojPYFgFFTLuI/edit

The get end-point exists for all the stocks but for **EUSM**, we might need to return only those inventory items which belong to the particular Service point. Therefore, we need to expose another end-point that would return a list of Stock against given location Id (i.e. the Service Point Id).                                   
@dubdabasoduba Please correct me if there is anything wrong! Thanks.

**Comment by rehammuzzamil** [comment]
For the delete end-point, soft delete will be performed, therefore a new column as date_deleted will be added in **stock table** and **stock_metadata table**. The record will be updated with the date deleted column whenever a call is made for a delete record.            cc: @dubdabasoduba @githengi
