### ISSUE TITLE
Stock API allow location filter 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#559]
- [ ] Stock API allow location filter 

- [ ]  This will be used to lookup stock when using a location(service point)

- [ ] The stock API should return all stock records with a valid accountability end date only for the requested location

**Comment by rehammuzzamil** [comment]
Please confirm the validity criteria for an accountability end date, is it correct to return only those stocks whose accountability end date is not passed yet? @cafootitt  @githengi

**Comment by cafootitt** [comment]
@rehammuzzamil That is correct.

**Comment by rehammuzzamil** [comment]
@dubdabasoduba  Can you please confirm, by Stock API does it mean to allow locationId filter in "/sync" and search end-point, as it takes StockSearchBean param?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba Can you please confirm, by Stock API does it mean to allow locationId filter in "/sync" and search end-point, as it takes StockSearchBean param?

@rehammuzzamil yes. That's correct
