### ISSUE TITLE
Location API add API to return direct location Parents with tags only

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#561]
Location API add an API to return direct location parents and ancestors with their location tags.

The API should accept location Id as the parameter

The ApI will be used to power the [service point details ](https://marvelapp.com/prototype/6agej0e/screen/73081456)

**Comment by rehammuzzamil** [comment]
As per discussion with @githengi, the API will return direct location Parents and ancestors with tags.
The API will take locationId in a @PathVariable and the service layer will get the parent of the location id provided in the path variable (let's say a parent is a), and get parent of a(let's say b), and so on. This process would be recursively run by a query, to find all the ancestors until there is no parent left. All the ancestors including the location itself would be returned in descending order in the query.
LocationTree object will be returned from the end-point.

**Comment by rehammuzzamil** [comment]
As per the PR feedback Set<LocationDetail> will be returned, as this maybe easier for the FE team.
