### ISSUE TITLE
Team unassignment and reassignment on the same day fails

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-server-web#573]
When a user assigns a team to a plan, then later removes the assignment of the the team to the plan, an attempt to assign the team to the plan second time fails with an error 400 

Related to https://github.com/onaio/reveal-frontend/issues/1335

**Comment by Rkareko** [comment]
@githengi another related issue is that there is some state where a team assignment is expired thus does not appear on the api but the duration spills over to the next day hence a new assignment cannot be made on the current day e.g a sample from Zambia prod

`  id   | organization_id | location_id | plan_id | from_date  |  to_date   |        duration         
-------+-----------------+-------------+---------+------------+------------+-------------------------
  7762 |             389 |       23227 |     120 | 2020-09-28 | 2020-10-11 | [2020-09-28,2020-10-12)
  7763 |             389 |       23237 |     120 | 2020-09-28 | 2020-10-11 | [2020-09-28,2020-10-12)
  7757 |             389 |       23238 |     120 | 2020-09-28 | 2020-10-11 | [2020-09-28,2020-10-12)`

**Comment by githengi** [comment]
@Rkareko testing on stage and assigning and un-assigning and repeating again and again is working
