### ISSUE TITLE
THAI LOCAL - There are no other users shown when one clicks on the user filter

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-server-web#575]
There are no other users shown when one clicks on the user filter
![image](https://user-images.githubusercontent.com/61143692/95622300-dc682500-0a7b-11eb-8856-af119621dfdb.png)
superset user

**Comment by Rkareko** [comment]
@moshthepitt @hmakandi @samkanga This should be working now

**Comment by moshthepitt** [comment]
Thanks @Rkareko
