### ISSUE TITLE
Zambia Production IRS tasks only generate for first 1000 structures in an OA

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-server-web#612]
Zambia Production
Jurisdiction Id: 3fe40fa0-c7b8-4ac2-8836-8ea3d278df51
Jurisdiction name: sean_1

This jurisdiction has 2196 structures. Tasks were generated only for the first 1000 structures.
Batch 1 = 1000 results https://reveal-zm.smartregister.org/opensrp/rest/task/sync?serverVersion=0&plan=d5cb7746-ecfe-557c-bbf4-4a3ccdcab23d&group=3fe40fa0-c7b8-4ac2-8836-8ea3d278df51
Batch 2 = 0 results https://reveal-zm.smartregister.org/opensrp/rest/task/sync?serverVersion=1600367084470&plan=d5cb7746-ecfe-557c-bbf4-4a3ccdcab23d&group=3fe40fa0-c7b8-4ac2-8836-8ea3d278df51

We expect tasks to generate for all structures in the operational area, not just the first 1000.

depends on https://github.com/OpenSRP/opensrp-server-core/issues/353

**Comment by Rkareko** [comment]
Resolved by https://github.com/OpenSRP/opensrp-server-web/pull/613
