### ISSUE TITLE
Search clients with attributes and location of registration.

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-server-web#622]
**Description** 

We would want to support search for clients using the location where they registered, at the same time filter the clients based on particular client attributes.

**Approach**
- Pass a list of locations and client attributes to the endpoint. Then get a list of clients whose location of registration match the provided list.
- Filter the clients clients based on the provided search parameters and return the results.

**Concern**
How will we represent the information? i.e. we also need to return part of the location details for each client in the response. Can we include the location details in the `ClientModel`?

**Comment by githengi** [comment]
For this we should add a location Id filter on the current client search endpoint.

This should return the locationId for each client. Is that enough @ellykits

**Comment by ellykits** [comment]
We only needed location id and the name.

**Comment by rehammuzzamil** [comment]
As per my understanding, we need to add support of additional request param of location id in an existing end-point of Search in ClientResource and update the `selectBySearchBean` query to add another condition for locationId in `CustomClientMetadataMapper.xml`.
@githengi  Please confirm, do request param can take a list of locations separated by delimiter or a single locationId?

**Comment by ellykits** [comment]
@rehammuzzamil 

> As per my understanding, we need to add support of additional request param of location id in an existing end-point of Search in ClientResource and update the `selectBySearchBean` query to add another condition for locationId in `CustomClientMetadataMapper.xml`

Exactly. @githengi Returning the location id would suffice.

**Comment by githengi** [comment]
> @githengi Please confirm, do request param can take a list of locations separated by delimiter or a single locationId?

a list of locationIds
