### ISSUE TITLE
Implement a Task Search API that optionally returns the number of tasks

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#628]
- [ ] Implement a Task Search API that optionally returns the number of tasks

- [ ] The API should accept the below  params

- plan identifier (mandatory)  
- a list group identifiers (optional)
- code (optional)
- status (optional)
- business status (optional)

- [ ] The API should by default return the tasks and counts in the header like other search endpoints

- [ ] The API should accept an optional boolean param that allows it to return the task counts only

Related to https://github.com/OpenSRP/web/issues/172

**Comment by rehammuzzamil** [comment]
As per my understanding, we need to expose an end-point on `TaskResource` which would return tasks data after querying the database and filtering the records based on the provided input fields. The API will accept the following parameters: 
planIdentifier, list of group identifiers (optional),code (optional) ,status (optional) ,business status (optional) ,returnTaskCountOnly (optional) 

By default, the API would return the tasks and counts in the header. But if the parameter of returnTaskCountOnly is provided as true, only the count of tasks will be returned and no data of tasks will be a part of the response payload. Wrt the implementation, a query will be defined to fetch tasks after meeting the criteria provided in request params and will be responsible to return tasks in the response payload. For count, a similar query will be referenced but this time only the count will be returned. 
For maintainability, a **search bean** would be defined to package all the request params in a single object. 

Support of pagination will also be provided.
