### ISSUE TITLE
Implement Event export API 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#637]
- [ ] Implement Event export API to be used to support mission data export https://github.com/OpenSRP/web/issues/174

- [ ] The API should be accept the eventType and Plan identifier and an optional date range( from and to) filter that it will use get the events.

- [ ] As per the csv sheets defined on https://github.com/OpenSRP/web/issues/174 custom rules need to be implemented to support the data export.

- [ ] Use the settings API to define the rules that will be used in exporting the csv

- [ ] The setting API will have an settings object per eventType that is to be exported. Columns that don't have mapping in the settings will be skipped. The setting will define the field( as jsonPath on the event json) and the label which will be column header

- [ ] Use a JSONPath library e.g https://github.com/json-path/JsonPath or Jackson to extract keys from the event json using JSON Path

- [ ] If setting is not defined on the API then all data on the event will be returned with obs flattened into columns for the CSV

- [ ] For each of  event Type passed, create a single CSV for each

- [ ] Compress the CSV to a ZIP file which should be downloaded on the API

**Comment by cafootitt** [comment]
This issue is paused until https://github.com/OpenSRP/opensrp-plan-evaluator/issues/83 is complete, which is higher priority

**Comment by cafootitt** [comment]
Reham working on this now.

**Comment by cafootitt** [comment]
Reham shared some sample csvs on Slack for Sam/Carolyn to review.

**Comment by rehammuzzamil** [comment]
Implementation details:
An API will download a single zip file, that unzips to CSV files of each event type passed in a param and a separate folder for the images for the `flag_problem` event. The product images folder will open and have sub-folders for each of the service points the inventory product images were collected for. 

To make it dynamic, we have defined settings configurations for the column data to be populated from the Event JSON in the CSV. The mapping document can be found here for further reference:
https://docs.google.com/document/d/1-mJOVHiI1azk4UNg9dwlqXD7amScHRAEDcSbi2rKhsk/edit

If the setting is not defined on the `event_type` then obs data will be flattened into the columns for the CSV. It is assumed to have a similar structure of JSON for a particular event type. For example, all event types of `looks_good` would have a similar JSON structure. This is essential since at the backend we are populating the header only once with the data taken from the first event JSON of the particular type.

If for an instance a key is defined in a settings configuration but is not present in an event JSON, that particular cell of that CSV would be empty.

As mutually discussed with @bennsimon, we concluded to have a Product Image Name for the `flag_problem` event in the following pattern: `stockid_planIdentifier`.

cc: @cafootitt  @githengi

**Comment by rehammuzzamil** [comment]
[event_type_to_settings_identifier.txt](https://github.com/OpenSRP/opensrp-server-web/files/5716451/event_type_to_settings_identifier.txt)
[settings_fix_problem_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5716455/settings_fix_problem_event.txt)
[settings_flag_problem_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5716457/settings_flag_problem_event.txt)
[settings_looks_good_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5716459/settings_looks_good_event.txt)
[settings_record_gps_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5716461/settings_record_gps_event.txt)
[settings_service_point_check_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5716462/settings_service_point_check_event.txt)

This is a pre-requisite step, which requires settings configurations to be posted to the server. These hold the mappings of the columns to the JSON keys of the Event.  
@githengi  Please review this! Thanks.
cc : @cafootitt  @p-netm  @bennsimon

**Comment by cafootitt** [comment]
@githengi needs to review PR changes and merge, then this can be closed.

**Comment by cafootitt** [comment]
This is blocking the mission data/indicator work.

**Comment by githengi** [comment]
PR reviewed

**Comment by rehammuzzamil** [comment]
**API Structure:**
URL : `rest/event/export-data `
RequestParams:
- List<String> eventTypes
- String planIdentifier
- String fromDate (optional)
- String toDate (optional)

For example:
`http://localhost:8080/opensrp/rest/event/export-data?eventTypes=flag_problem,service_point_check,looks_good,record_gps,fix_problem&planIdentifier=335ef7a3-7f35-58aa-8263-4419464946d8
`
Produces = "application/zip" file

The response would be a zip file. If there is no data in the server, a zip file will still be returned with the empty CSV files inside.
@kahummer Please review this for your reference.
cc: @p-netm @cafootitt @githengi

**Comment by rehammuzzamil** [comment]
The mapping of  locationId  i.e Service Point Location Id from `$.locationId` to `$.details.locationId `has been changed by client-side (Android). Therefore, the updated settings_configurations payloads are attached : 

[event_type_to_settings_identifier.txt](https://github.com/OpenSRP/opensrp-server-web/files/5864576/event_type_to_settings_identifier.txt)
[settings_fix_problem_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5864577/settings_fix_problem_event.txt)
[settings_flag_problem_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5864579/settings_flag_problem_event.txt)
[settings_looks_good_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5864580/settings_looks_good_event.txt)
[settings_record_gps_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5864582/settings_record_gps_event.txt)
[settings_service_point_check_event.txt](https://github.com/OpenSRP/opensrp-server-web/files/5864583/settings_service_point_check_event.txt)

It is a pre-requisite step that requires settings configurations to be posted to the server.
cc: @cafootitt  @githengi @bennsimon @p-netm @kahummer

**Comment by rehammuzzamil** [comment]
The old settings can be removed by running this query, I would suggest confirming from @githengi before doing so. 
The queries are :

```
delete from core.settings where json ->> 'identifier' in 
('event_type_to_settings_identifier', 'event_type_flag_problem',
'event_type_fix_problem',
'event_type_looks_good',
'event_type_record_gps',
'event_type_service_point_check');
```

```
delete from core.settings_metadata where identifier in
('event_type_to_settings_identifier', 
'event_type_flag_problem',
'event_type_fix_problem',
'event_type_looks_good',
'event_type_record_gps',
'event_type_service_point_check');
```

New settings can be posted afterward.
@cafootitt  @p-netm
