### ISSUE TITLE
Use Partial Url to save product Image in product catalogue table

### ISSUE THREAD

**Issue by bennsimon** [OpenSRP/opensrp-server-web#645]
Using the whole URL might bring issues when the domain changes or endpoint is updated.

**Comment by cafootitt** [comment]
2 issues:
- using the whole domain
- use of https

**Comment by githengi** [comment]
https shouldn't be a problem since our servers should always rewrite to https.
From the code we cannot be able to get the https URL since tomcat runs on http and nginx on https. 
The request via http should work and the image should be returned.

**Comment by rehammuzzamil** [comment]
As per discussion with @githengi, photoUrl should be returned with a domain in a GET call and should not be persisted in a database along with a domain.
