### ISSUE TITLE
The service point Id should be the structure Id in add inventory flow

### ISSUE THREAD

**Issue by rehammuzzamil** [OpenSRP/opensrp-server-web#650]
Update validation on `opensrp/rest/stockresource/` Add Inventory end-point to accept service point id which is a valid structure id, not a location Id.
cc: @bennsimon

**Comment by cafootitt** [comment]
@rehammuzzamil @githengi I'm unable to QA this myself. Is this tested and can I close this issue?

**Comment by rehammuzzamil** [comment]
Its core PR has been approved and merged to master, but it would be effective when corresponding web PR will be merged.
It would be covered in the scope of https://github.com/OpenSRP/opensrp-server-web/pull/657 (PR for the server web for[ Issue # 83](https://github.com/OpenSRP/opensrp-plan-evaluator/issues/83))
