### ISSUE TITLE
Return Failed Ids on event sync

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-web#653]
Return Failed Ids on event sync. 

This will remove the need for the client to make a second call to validate if records were saved on the server.

**Comment by githengi** [comment]
Project: Opensrp Core

**Comment by rehammuzzamil** [comment]
Could you please provide more information regarding this issue? 
As per my understanding, both get and post end-points for sync fetches data from the server. I see the method `private void searchMissingClients(List<String> clientIds, List<Client> clients, long startTime)` which computes missing client ids. But by default searchMissingClients, param is false in opensrp.properties.  Do we need to return that id's in a response payload?
@githengi Please share your feedback.

**Comment by rehammuzzamil** [comment]
Could you please redirect me to the end-point? As per my initial understanding, all three end-points `/sync  (GET and POST) and /sync-by-base-entity-ids` returns data from the server and nothing is being posted to the server. Could you please confirm if it is something related to the` /add `end-point?
@githengi

**Comment by githengi** [comment]
> Could you please provide more information regarding this issue?
> As per my understanding, both get and post end-points for sync fetches data from the server. I see the method `private void searchMissingClients(List<String> clientIds, List<Client> clients, long startTime)` which computes missing client ids. But by default searchMissingClients, param is false in opensrp.properties. Do we need to return that id's in a response payload?
> @githengi Please share your feedback.

Yes we need to return Ids that were not saved i.e there was error on saving the record. 
`searchMissingClients(List<String> clientIds, List<Client> clients, long startTime` is deprecated and is not used

**Comment by githengi** [comment]
> Could you please redirect me to the end-point? As per my initial understanding, all three end-points `/sync (GET and POST) and /sync-by-base-entity-ids` returns data from the server and nothing is being posted to the server. Could you please confirm if it is something related to the`/add`end-point?
> @githengi

Yes its `/add` end-point
