### ISSUE TITLE
Missing Support for description field in the planDefnition schema

### ISSUE THREAD

**Issue by p-netm** [OpenSRP/opensrp-server-web#658]
**Process**:
post a plan definition with a description field, 
get the same plan by using its id

**Expectation**:
- receive the same exact plan

**Actual**:
- the plan received is missing the description field

The updated and full schema for plans can be found here: OpenSRP/web#180

**Comment by rehammuzzamil** [comment]
Its fix would be a part of the following PR in the plan-evaluator library:
https://github.com/OpenSRP/opensrp-plan-evaluator/pull/85/files
cc : @githengi

**Comment by githengi** [comment]
@cafootitt can this be closed?
