### ISSUE TITLE
Add a POST endpoint for stock sync api with locations param

### ISSUE THREAD

**Issue by bennsimon** [OpenSRP/opensrp-server-web#662]
Currently, we use a GET request to fetch stocks from `/rest/stockresource/sync` adding a `locations` param (comma separated structure-ids) can become very large for the GET request.

Am suggesting we add a POST request if we need the `locations` filter.

**Comment by rehammuzzamil** [comment]
As discussed, a POST-end-point for `/sync` will be exposed to the stock resource. The existing GET end-point will remain as is for backward compatibility.
