### ISSUE TITLE
Support a draft CSV inventory upload state

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#670]
We need to support a draft state of inventory items during the bulk csv upload workflow. I.e. on this step: https://marvelapp.com/prototype/f3igd3h/screen/75791256, the user is informed that the csv inventory has successfully validated, but before the data is persisted, the user needs to confirm this action by tapping on the "Confirm inventory updates" button.

I understand we need to make API changes to support this draft state. @rehammuzzamil to fill in further implementation details required.

**Comment by rehammuzzamil** [comment]
As per my initial investigation and discussion in the standup meeting, we need to break an existing import inventory data API (`/import/inventory`) into two parts: 
- One is responsible to validate the CSV file and return the summary based on the validation results. The summary can be a CSV file that returns the list of failed rows along with the errors in case of validation failed or a String which returns "X inventory items will be added." _(needs to be finalized)_
- Another API will be created which will be triggered when a user clicks on the "Confirm inventory updates"  button, which would actually persist the data to the server.

cc: @githengi  Please share your feedback.

**Comment by cafootitt** [comment]
1. API validation
2. Processing of data in the server
Reham will start work on this on Monday, Jan 11th.

**Comment by rehammuzzamil** [comment]
**1- Validate Inventory:**
   URL : `rest/stockresource/inventory/validate`
   Method : POST
   Accepts multipart/form-data
   
   Successful Response:
   Status : 200 (OK)
   Body : 
```
   {
    "rowCount": 2
   }
   
```
   Error Response:
   Status : 400 (Bad Request)
   Body : CSV File
   Attached is a response file.
   
**2- Persist Inventory:**
   URL :` /rest/stockresource/import/inventory`
   Method : POST
   Accepts multipart/form-data 
   
   Successful Response:
   Status : 200 (OK)
   Body: CSV File
   
   Error Response:
   Status: Bad Request
   Body: CSV File
`   I am trying to reproduce a failed record scenario while the persistence of data. But the structure would be the same as in (1)'s error response. `
@p-netm Please review this for your reference.
cc: @githengi
