### ISSUE TITLE
Adjust geographic levels on EUSM imported location data

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#673]
We need to refer to geographic level to identify the list of districts to return for user selection during plan location assignment. Currently, all locations/jurisdictions have geographic level of 0. Below is the geographic levels in the country. Would we start at level 0 or level 1?

0 - Country
1 - Region
2 - District
3 - Commune
4 - Service point

OR

1 - Country
2 - Region
3 - District
4 - Commune
5 - Service point

**Comment by mberg** [comment]
I'm not clear on what the question is.  I'm not sure if the number is
something that our location hierarchy system uses.  That may be
abstracted away from the user.  Can you provide a bit more clarity on how
the number value is going to be used?  Are we listing the level number in a
CSV upload or something?

**Comment by cafootitt** [comment]
@mberg This isn't for the user to see or consume in any way. We are using it in the back-end to return the list of districts for the user to select during plan location assignment. Right now, all locations have a geographic level of 0 by mistake, so this is just a quick fix for Sam G. to help us with next week, to unblock plan location assignment work.

**Comment by githengi** [comment]
Geographical levels updated

**Comment by cafootitt** [comment]
Great, thanks Sam.
