### ISSUE TITLE
RVL-1400 - Extend expiry date for Macepa Plans

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-server-web#678]
Akros would like to extend the duration of the present plans to 15th February. Below is the breakdown of the plan name, ID and the new end date:

1. MACEPA: Full Reveal 2020 IRS Plan - 4cbe10b9-231e-5084-9646-0a923dcfa0da - 28 February 2021
2. MACEPA IRS-Lite Western Live Plan - 19e55ac1-06c4-4c71-9e93-2905d54d093a - 28 February 2021
3. MACEPA IRS-Lite Southern Live Plan - 88d4f46e-5fd0-4a02-967f-57624584ab8b - 28 February 2021

**Comment by Rkareko** [comment]
@samkanga The updates have been made

**Comment by samkanga** [comment]
Thanks. These look all good. I will go ahead and close the ticket.
