### ISSUE TITLE
Upload json form is throwing a 400 error RVL-339

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-server-web#688]
1. Login to web stage: https://web.reveal-stage.smartregister.org/manifest/file-upload
2. Go to admin- releases and click on upload form.
3. Upload a json form.
4. I uploaded a blodd screening json form.
5. Click upload.
6. Observe the error.

![image](https://user-images.githubusercontent.com/5908630/105195398-a5f67780-5b4b-11eb-9bc0-4d2f1490b87b.png)

**Comment by dubdabasoduba** [comment]
- [ ] When the files are edited via a windows machine then the validation on the server says it's not a valid YAML. This is only happening for YAML files. I think we have an issue with the encoding we are using on the code to validate the files

**Comment by Rkareko** [comment]
@dubdabasoduba cc @samkanga @githengi when YML files are uploaded on windows machines the content type received on the server is `application/octet-stream` that is why they are failing validation. Would the fix be applied on the Front End i.e updating the headers?

**Comment by githengi** [comment]
@Rkareko how about accepting and parsing application/octet-stream to check if its a valid yaml file if the file has a yml extention. i.e checking the content type for the uploaded file
