### ISSUE TITLE
Bug on serverVersion filtering on /rest/product-catalogue

### ISSUE THREAD

**Issue by bennsimon** [OpenSRP/opensrp-server-web#698]
serverVersion should be applied for greater than or equal to the value supplied but now its greater than only.

**Comment by cafootitt** [comment]
@rehammuzzamil Can pick this up when back from leave.

**Comment by rehammuzzamil** [comment]
Hi @bennsimon, As per my investigations at the code level whenever the server version is provided in the `/rest/product-catalogue` end-point, search criteria are populated through the parameters passed in the API. For the `serverVersion` criteria is defined to be greater than or equal to. 
I have tested with a unit test for the testing purpose in my local environment.
Attached is a screenshot for your reference. Please correct me if there is anything else.
![serverversiongreaterthanorequalto](https://user-images.githubusercontent.com/62061579/107188453-7e3b5680-6a09-11eb-92ee-7f75912f5ff3.png)

Thanks!
cc: @cafootitt

**Comment by rehammuzzamil** [comment]
The issue also exists on `/rest/stockresource/sync` GET end-point. As per the investigation, this is the conventional approach followed throughout the APIs. The sync API for the product catalogue also follows this approach. After discussion with @bennsimon, we concluded that syncV2 should also follow the same conventional approach. 
[https://github.com/OpenSRP/opensrp-server-web/blob/9f52d7b3af0a4ddc2748086fac5269b[…]271af1acb/src/main/java/org/opensrp/web/rest/StockResource.java (e]

cc: @githengi

**Comment by githengi** [comment]
@rehammuzzamil and @bennsimon the increment should be done on android, newer APIs dont increment the serverVersion, that is handled by the clients

**Comment by rehammuzzamil** [comment]
@githengi Should I remove increment logic on product catalogue then from the API?

**Comment by cafootitt** [comment]
Changes:
- Product catalogue sync endpoint - incrementing logic of server version removed from server side and done on the client end instead (@bennsimon)

**Comment by rehammuzzamil** [comment]
Made a fix in this PR https://github.com/OpenSRP/opensrp-server-web/pull/716.
@bennsimon Can you please create an issue to handle incremental logic at the client end for Product Catalogue get API?
