### ISSUE TITLE
Update Settings Functionality to Allow Large Number of Settings to be Posted

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-server-web#705]
When uploading a csv file with many locations such as the case of Zambia, the user is experiencing an error 500 with the message `{"message":"The server encountered an error processing the request.","status":"500 INTERNAL_SERVER_ERROR","data":null,"success":false}` The investigation revealed that the error is associated with the size of the file being uploaded. With very large settings, the attempt to insert all the settings with 1 query, might exceed parameters for a single query.

**Comment by Naima-Bashir** [comment]
This has passed QA
