### ISSUE TITLE
Add an API endpoint for Jurisdictions without Geometry

### ISSUE THREAD

**Issue by cKellyDesign** [OpenSRP/opensrp-server-web#71]
Add an API endpoint for Jurisdictions without Geometry for faster non-map related requests for jurisdiction information.

This endpoint should return basic information about the jurisdiction without (or with) GeoJSON, ideally with the ability to filter by properties and to chose which properties are returned.

**Requested Fields**
* id
* geographic_level
* parent_id
* name
* geometry (if we are able to chose which fields are returned)

**Comment by githengi** [comment]
@cKellyDesign please share a sample expected response for the endpoint

Also for being able to filter by properties can we add a properties param e.g
sample query would be  `property_name1:value1,property_name2:value2`

The properties to be returned can be a list(comma delimited) passed to the API endpoint

**Comment by githengi** [comment]
@cKellyDesign have started implementation of the API

It has these 3 params  

-  boolean `is_jurisdiction`  determines fn query is for jurisdictions or structures 
-  boolean `return_geometry`  determines if geometry will be returned
- list `properties_filter` which the list of properties filter to be applied e.g `name:name1,parentId:1234`

This will return a JSON list of Locations which may have geometry or not depending on param `return_geometry`

For now i have not Scoped returning a subset of the location properties. Is this currently required

**Comment by cKellyDesign** [comment]
@githengi Fantastic, I think `is_jurisdiction` and `return_geometry` will be enough, at this point I think the `properties_filter` seems like a nice-to-have.

**Comment by moshthepitt** [comment]
@cKellyDesign dont we want to filter by parent_id or something like that?

**Comment by githengi** [comment]
I @cKellyDesign @moshthepitt I will develop the `properties_filter` since it will also work for #75

**Comment by githengi** [comment]
> @cKellyDesign dont we want to filter by parent_id or something like that?

@moshthepitt this would return the direct children and not necessarily all the other lower levels below the children
