### ISSUE TITLE
Add the product's name to the stock get response

### ISSUE THREAD

**Issue by p-netm** [OpenSRP/opensrp-server-web#711]
current response from api
```
{
    type: 'Stock',
    serverVersion: 12,
    identifier: '2',
    providerid: '34615126-f515-4b31-80ee-c42227f6f0c5',
    value: 1,
    version: 1610612387610,
    deliveryDate: 'Jan 2, 2020, 3:00:00 AM',
    accountabilityEndDate: 'May 2, 2021, 3:00:00 AM',
    donor: 'ADB',
    serialNumber: '123434',
    locationId: 'b8a7998c-5df6-49eb-98e6-f0675db71848',
    customProperties: { 'PO Number': '101', 'UNICEF section': 'Health' },
    _id: '69227a92-7979-490c-b149-f28669c6b760',
    _rev: 'v1',
    transaction_type: 'Inventory',
  }
```
  I would like to request we add the product's name as well to the response,

**Comment by bennsimon** [comment]
@rehammuzzamil So for this i was thinking we could add the whole product body to the request so that the body would look like this.
```json
{
    type: 'Stock',
    serverVersion: 12,
    identifier: '2',
    providerid: '34615126-f515-4b31-80ee-c42227f6f0c5',
    value: 1,
    version: 1610612387610,
    deliveryDate: 'Jan 2, 2020, 3:00:00 AM',
    accountabilityEndDate: 'May 2, 2021, 3:00:00 AM',
    donor: 'ADB',
    serialNumber: '123434',
    locationId: 'b8a7998c-5df6-49eb-98e6-f0675db71848',
    customProperties: { 'PO Number': '101', 'UNICEF section': 'Health' },
    _id: '69227a92-7979-490c-b149-f28669c6b760',
    _rev: 'v1',
    transaction_type: 'Inventory',
    product: {  'name': 'Product A', 'uniqueId': 3, ... }
  }
```

**Comment by rehammuzzamil** [comment]
There could be two possibilities:

1. We can have a single object for both stock and product details like  this
```
{
	"stock": {
		"identifier": "1",
		"vaccine_type_id": null,
		"transaction_type": "Inventory",
		"providerid": "3c11c3ad-c366-443f-8ca8-c8c21f5bdd22",
		"value": 10,
		"date_created": 1520892000000,
		"to_from": null,
		"date_updated": null,
		"version": 1606748740346,
		"deliveryDate": "Jun 6, 2020, 12:00:00 AM",
		"accountabilityEndDate": "Jun 21, 2021, 12:00:00 AM",
		"donor": "ADB",
		"serialNumber": "1234serial",
		"locationId": "90397",
		"customProperties": {
			"PO Number": "111",
			"UNICEF section": "Health"
		},
		"creator": null,
		"dateCreated": null,
		"editor": null,
		"dateEdited": null,
		"voided": null,
		"dateVoided": null,
		"voider": null,
		"voidReason": null,
		"serverVersion": 1521112142815,
		"clientApplicationVersion": null,
		"clientDatabaseVersion": null,
		"type": "Stock",
		"id": "7e278a0d-a4eb-4d23-aea0-836d813836a5",
		"revision": null,
		"conflicts": null
	},
	"productCatalogue": {
		"uniqueId": 1,
		"productName": "School supplies",
		"isAttractiveItem": true,
		"materialNumber": "MX-1234",
		"availability": "Yes available",
		"condition": "Not in a good condition",
		"appropriateUsage": "Yes",
		"accountabilityPeriod": 12,
		"photoURL": "",
		"serverVersion": null
	}
}
```
This would require a separate new API to be exposed.
2. The second option is to add a ProductCatalogue field in the Stock object and get corresponding product catalogue details from the database and populate them in the stock's product catalogue field in the stock `/sync `end-point. The payload would looks like the above as @bennsimon  shared.

@githengi What do you think is the better approach to solve this problem?
cc : @p-netm  @bennsimon

**Comment by githengi** [comment]
@rehammuzzamil 
Adding the product to the stock should be okay. However I think the activation should by an optional boolean param e.g return_product, when not specified stocks are returned as is, when specified with a value of true then return product nested within each stock object

**Comment by rehammuzzamil** [comment]
@p-netm Please confirm you need product name in the following API response? 
`rest/stockresource/servicePointId/{servicePointId} `

**Comment by rehammuzzamil** [comment]
Hi @p-netm , Following is a sample response payload of `/rest/stockresource/servicePointId/90397?returnProduct=true` end-point. If you want products details in the response payload, please send **returnProduct** param as true.

```
[
    {
        "type": "Stock",
        "serverVersion": 1521112141443,
        "identifier": "2",
        "providerid": "d1a5c891-95d5-492c-be1d-646b22b58854",
        "value": 10,
        "version": 1612864053002,
        "deliveryDate": "Feb 6, 2021, 5:00:00 AM",
        "accountabilityEndDate": "Apr 6, 2021, 5:00:00 AM",
        "donor": "ADB",
        "serialNumber": "12345",
        "locationId": "90397",
        "customProperties": {
            "PO Number": "17",
            "UNICEF section": "Health"
        },
        "product": {
            "uniqueId": 2,
            "productName": "Change name Test",
            "isAttractiveItem": true,
            "materialNumber": "MK-123",
            "availability": "available",
            "condition": "yes",
            "appropriateUsage": "yes",
            "accountabilityPeriod": 2,
            "photoURL": "",
            "serverVersion": 123346
        },
        "_id": "993baee2-0357-487a-9765-9395efed9eb7",
        "_rev": "v1",
        "transaction_type": "Inventory"
    }
]
```
Please let me know if it looks okay.

**Comment by p-netm** [comment]
> Hi @p-netm , Following is a sample response payload of `/rest/stockresource/servicePointId/90397?returnProduct=true` end-point. If you want products details in the response payload, please send **returnProduct** param as true.
> 
> ```
> [
>     {
>         "type": "Stock",
>         "serverVersion": 1521112141443,
>         "identifier": "2",
>         "providerid": "d1a5c891-95d5-492c-be1d-646b22b58854",
>         "value": 10,
>         "version": 1612864053002,
>         "deliveryDate": "Feb 6, 2021, 5:00:00 AM",
>         "accountabilityEndDate": "Apr 6, 2021, 5:00:00 AM",
>         "donor": "ADB",
>         "serialNumber": "12345",
>         "locationId": "90397",
>         "customProperties": {
>             "PO Number": "17",
>             "UNICEF section": "Health"
>         },
>         "product": {
>             "uniqueId": 2,
>             "productName": "Change name Test",
>             "isAttractiveItem": true,
>             "materialNumber": "MK-123",
>             "availability": "available",
>             "condition": "yes",
>             "appropriateUsage": "yes",
>             "accountabilityPeriod": 2,
>             "photoURL": "",
>             "serverVersion": 123346
>         },
>         "_id": "993baee2-0357-487a-9765-9395efed9eb7",
>         "_rev": "v1",
>         "transaction_type": "Inventory"
>     }
> ]
> ```
> 
> Please let me know if it looks okay.

@rehammuzzamil sorry seeing this only now, 
yeah this will work, thank you.

**Comment by cafootitt** [comment]
@rehammuzzamil submitting PR today.
