### ISSUE TITLE
Fix settings adaptation on the master branch

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#719]
- [ ] Settings do not resolve when running the master branch.  My guess is the location hierarchy is not generated as expected.

- When fetching settings if the `resolve` query param is set to `true` then any child location should inherit any settings not set for its location from the parent location. 
- This happens on the v2.1 branch as demonstrated on https://anc-stage.smartregister.org/opensrp/ but is broken on the master branch. The issue might be the difference in how we create the location hierarchies. 

**How to replicate**

- Fetch the settings using this [endpoint](https://anc-stage.smartregister.org/opensrp/rest/v2/settings/?identifier=population_characteristics&locationId=02ebbc84-5e29-4cd5-9b79-c594058923e9&resolve=true&serverVersion=0). This will give all the population characteristics  from the root location. Then change the location id to `b1ef8a0b-275b-43fc-a580-1e21ceb34c78` this will also bring you the settings from the root location `02ebbc84-5e29-4cd5-9b79-c594058923e9` and any other settings specific for this locations.  --- uses v2.1 branch
- Now try the same on the following [endpoint](https://opensrp-stage.smartregister.org/opensrp/rest/v2/settings?identifier=population_characteristics&locationId=b652b2f4-a95d-489b-9e28-4629746db96a&resolve=true&serverVersion=0) locationid to update to `35bf4771-a404-4220-bd9e-e2916decc116` -- This uses master branch

**Comment by rehammuzzamil** [comment]
As per my investigations, the settings are not being fetched from the parent locations is due to the location hierarchy is not generated as expected. On the Master branch hierarchy is created with the descendants. The solution is to build a Location Tree hierarchy with Ancestors @dubdabasoduba
