### ISSUE TITLE
Support pagination on /getAll Location API

### ISSUE THREAD

**Issue by rehammuzzamil** [OpenSRP/opensrp-server-web#723]
- [x] Support pagination on getAll Location API to fetch service points
- [x] This will allow fetching service points in a paginated way which will improve performance issues

End-point:
/rest/location/getAll?is_jurisdiction=false
cc : @p-netm @githengi

**Comment by rehammuzzamil** [comment]
We need to provide pagination support in `/rest/location/getAll?is_jurisdiction=false` GET end-point. Wrt implementation, new request params will be added in the API, i.e.` pageNumber, orderByFieldName, OrderByType`;
The `limit` param already exists, based on which the number of rows is returned.

Based on the input parameters provided by pageNumber and limit request params, offset and limit will be calculated and passed to the query to perform Row-bound pagination only on the `findAllStructures` query.

If the orderByType and orderByFieldName are not provided, the default value of orderByClause is used which is currently defined as `server_version asc.`

Moreover, If the page number param is not provided, records will be returned based on the default limit size (25 - as currently defined) to ensure backward compatibility. If we provide page number and limit (by the term limit we mean a number of records per page) records will be returned paginated and the API needs to be triggered for the next page every time. @githengi  is this correct?
cc: @p-netm

**Comment by cafootitt** [comment]
Both PRs assigned for review by @githengi

**Comment by cafootitt** [comment]
This was deployed. @p-netm or @kelvin-muchiri to test and close this issue and move to "Done" column when it passes QA.
