### ISSUE TITLE
Plan evaluator didn't get triggered for service point when mission was activated

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#728]
Investigate why plan evaluator did not trigger the tasks for the `Ambaliha 1` service point when `Carolyn's 18 Feb 2021 mission` was activated.

After @bennsimon manually triggered the plan for this service point, there are still issues:

- Record GPS task is appearing, when it shouldn't (Ambaliha 1 has known GPS points, so this task should not have been triggered)
- The tasks for the 5 inventory items in the service point are not appearing. According to the inventory list, there should be 5 product check tasks appearing: https://web.mg-eusm-staging.smartregister.org/inventory/profile/ba654fee-c497-478b-8aa1-cc570cc98c7d

![Screenshot_20210219-104155_eusm](https://user-images.githubusercontent.com/3488986/108494517-9fa40a00-7275-11eb-8eaa-5f4629ff893f.jpg)

**Comment by rehammuzzamil** [comment]
The plan evaluator might not have triggered due to the `plan.evaluation.enabled=false` property as false in` opensrp.properties` in configs.

**Comment by bennsimon** [comment]
> The plan evaluator might not have triggered due to the `plan.evaluation.enabled=false` property as false in` opensrp.properties` in configs.

@rehammuzzamil I dont think thats the issue though, On updatePlan the planEvaluation is only triggered when new jurisdictions are added.

**Comment by bennsimon** [comment]
@p-netm Do you use `PUT` or `POST` to update a plan.

**Comment by rehammuzzamil** [comment]
One of the parts of this issue is covered under the scope of https://github.com/OpenSRP/opensrp-plan-evaluator/issues/118 and the PR of the plan-evaluator is merged. But it will be affected when the corresponding core PR is merged. @cafootitt

**Comment by rehammuzzamil** [comment]
> > The plan evaluator might not have triggered due to the `plan.evaluation.enabled=false` property as false in` opensrp.properties` in configs.
> 
> @rehammuzzamil I dont think thats the issue though, On `updatePlan` of an `Active` plan planEvaluation is only triggered when new jurisdictions are added.

Yes that is correct.

**Comment by cafootitt** [comment]
In summary, this issue was being caused by 3 things:

- Plan Evaluator Serial Number Bug prevented product tasks to be created ... has been fixed here https://github.com/OpenSRP/opensrp-plan-evaluator/issues/118
- Product Check action missed in the plan being used.
- Update plan only triggers planEvaluation when jurisdictions are modified

**Comment by cafootitt** [comment]
@p-netm The actions for plans are hidden on EUSM web, so regarding "Product Check action missed in the plan being used." point above, we might need to look into that on the front end side then.

@githengi Can you clarify what the 3rd point above means? In EUSM, we're encountering an error because tasks are not getting triggered in EUSM, and Benn's identified this as a reason.

**Comment by cafootitt** [comment]
Next steps:
- Re-test this once the new server web deployment is done, as this could be affecting task generation for all products.
- Re-test activating a plan without any jurisdiction assignments. Then add area assignments. If this is an issue, we can add logic whereby plan cannot be activated unless at least one area is assigned. Sam G recommends we can maintain the flow (so allow plan activation without any assignments).

**Comment by cafootitt** [comment]
replaced by https://github.com/OpenSRP/web/issues/485
