### ISSUE TITLE
Parent location ID issue for Ambahita

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#734]
So there is an issue with `Ambahita` its parent should be `Bekily` but it isn't. We're investigating why this is, even though the correct parent location is showing in eusm web: https://web.mg-eusm-staging.smartregister.org/inventory/profile/db275086-3355-45cc-ab39-5c2f8f0e8fbc

**Comment by githengi** [comment]
The parents have been updated to reflect the correct parents
