### ISSUE TITLE
Post settings configurations to the stage server for export mission data flow

### ISSUE THREAD

**Issue by rehammuzzamil** [OpenSRP/opensrp-server-web#737]
- The settings API will have a settings object per eventType that is to be exported 
- Columns of each CSV file will be based on the columns defined in the settings payload
- Remove if there exist old settings against these identifiers https://github.com/OpenSRP/opensrp-server-web/issues/637#issuecomment-766900882
- Post new updated settings as defined here: 
https://github.com/OpenSRP/opensrp-server-web/issues/637#issuecomment-766576957

cc : @cafootitt

**Comment by bennsimon** [comment]
@cafootitt done
