### ISSUE TITLE
Allow search of structure with house number

### ISSUE THREAD

**Issue by Wambere** [OpenSRP/opensrp-server-web#75]
Nifi needs to be able to search for a particular structure in OpenSRP using just the house number

**Comment by githengi** [comment]
@Wambere Can we use the approach of  #71 to allow query by any location property since house number is a location property?

**Comment by Wambere** [comment]
@githengi yes, that's fine with me

**Comment by craigappl** [comment]
@Wambere and @githengi don't we want to search by properties.externalId as defined in this field in the data dictionary? https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=0&range=B19

**Comment by githengi** [comment]
@craigappl when developed #71 will allow search by any location properties such as `properties.externalId `
