### ISSUE TITLE
Investigate mission data download failure

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#771]
Mission name: Mission test EUSM #1 fevrier WASH / DLM

As per the quick investigation by @rehammuzzamil of export mission data download failure, the issue seems to be due the / in the mission name. Paths are separated with the slash and since there is no directory of dlm , this is causing the issue. I would suggest to restrict using / (slash) in the mission name so that we can avoid such issues. Any other solutions would be appreciated

`Exception occurred : /home/opensrp/tomcat-opensrp/temp/mission_test_eusm_#1_fevrier_wash_/_dlm_2021-03-05.zip (No such file or directory)`

**Comment by cafootitt** [comment]
Replaced with this issue: https://github.com/OpenSRP/web/issues/533

**Comment by rehammuzzamil** [comment]
@bennsimon Can you please these queries on the stage server of EUSM.
update core. plan
set json = jsonb_set(json, '{name}', '"Mission test EUSM #1 fevrier WASH or DLM"')
where id = 37;

update core. plan
set json = jsonb_set(json, '{title}', '"Mission test EUSM #1 fevrier WASH or DLM"')
where id = 37;

update core. plan
set json = jsonb_set(json, '{description}', '"Mission test EUSM #1 fevrier WASH or DLM"')
where id = 37;

cc : @cafootitt
