### ISSUE TITLE
Allow deleting of jurisdiction metadata whose value is blank/empty

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-server-web#772]
Related to https://github.com/onaio/reveal-frontend/issues/1514

We need a way to delete jurisdiction metadata.
The proposed solution is to delete entries where the `value` field is blank/empty.
Modify the current logic for  CSV upload endpoint  to delete the settings metadata  record where the `key` is equal to the value specified in the payload and the `value` field in the payload is blank/empty

An example of such a payload is 

```
{
  settingConfigurations:
    [
      {
        "_id": "109efe73-cf30-5025-82ee-4b9d436446a4",
        "identifier": "jurisdiction_metadata-structures",
        "settings": [
          {
            "description": "Jurisdiction Metadata for Siachitema id 453b01db-ab9e-4ad9-8300-0b6641529ac9",
            "key": "453b01db-ab9e-4ad9-8300-0b6641529ac9",
            "label": "Siachitema",
            "uuid": "1f5ead08-4b2c-5888-98cb-98858bea371d",
            "value": ""
          }
        ],
        "type": "SettingConfiguration"
      },
    ]
}
```

**Comment by Rkareko** [comment]
@ciremusyoka Please provide the endpoint the WEB UI uses for this

**Comment by ciremusyoka** [comment]
@Rkareko `/rest/settings/sync`

**Comment by Rkareko** [comment]
1- @ciremusyoka  In issue it is mentioned to modify the current logic for CSV upload endpoint, but the end-point used by the web UI is /rest/settings/sync , it takes a string payload as you mentioned in the issue (and not the CSV). Confirm this.

@ciremusyoka , @dubdabasoduba @Rkareko views on the following :-
2- Should we also ignore saving new settings when value field is blank and the identifier is one of the mentioned ones?
3- Or should we only check while adding/updating to check if the records already exists, if they exist we need to check its value field and if found as blank delete that entry.

**Comment by ciremusyoka** [comment]
> 1- @ciremusyoka In issue it is mentioned to modify the current logic for CSV upload endpoint, but the end-point used by the web UI is /rest/settings/sync , it takes a string payload as you mentioned in the issue (and not the CSV). Confirm this.
> 
@Rkareko the web takes in a csv as input and converts it into a settings payload before posting to /rest/settings/sync

**Comment by dubdabasoduba** [comment]
> 1- @ciremusyoka In issue it is mentioned to modify the current logic for CSV upload endpoint, but the end-point used by the web UI is /rest/settings/sync , it takes a string payload as you mentioned in the issue (and not the CSV). Confirm this.
> 
> @ciremusyoka , @dubdabasoduba @Rkareko views on the following :-
> 2- Should we also ignore saving new settings when value field is blank and the identifier is one of the mentioned ones?
> 3- Or should we only check while adding/updating to check if the records already exists, if they exist we need to check its value field and if found as blank delete that entry.

I think we can go with 2.  
For 3 how do you know from the csv that you have to update? Does the csv have `uuid`s?

**Comment by dubdabasoduba** [comment]
if we have to delete them we need to get the `settingMetadataId` and then delete that specific metadata.

**Comment by Rkareko** [comment]
@ciremusyoka does the web always have the `settingMetadataId` when making the request ?

**Comment by Rkareko** [comment]
@dubdabasoduba if the payload does not have an existing `settingMetadataId` can we use a combination of the `identifier` and `setting_key` to figure out which record to delete?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba if the payload does not have an existing `settingMetadataId` can we use a combination of the `identifier` and `setting_key` to figure out which record to delete (for option 3)?

I assume this is the settings `identifier` and the `setting_key` right? Could you throw in the `locationId` to if present this is because if the settings are adapted then you will find a setting with the same `identifier`, `setting_key` 

The `locationId` helps clearly identifier the setting metadata.

**Comment by Rkareko** [comment]
> > @dubdabasoduba if the payload does not have an existing `settingMetadataId` can we use a combination of the `identifier` and `setting_key` to figure out which record to delete (for option 3)?
> 
> I assume this is the settings `identifier` and the `setting_key` right? Could you throw in the `locationId` to if present this is because if the settings are adapted then you will find a setting with the same `identifier`, `setting_key`
> 
> The `locationId` helps clearly identifier the setting metadata.

@ciremusyoka is this something that is possible. We need to iron this out before work starts

**Comment by moshthepitt** [comment]
```json
{
    "settingConfigurations": [
        {
            "_id": "fc17ac3e-ffea-55d4-902c-3069d675c198",
            "identifier": "jurisdiction_metadata-population",
            "settings": [
                {
                    "description": "Jurisdiction Metadata for chs_1(2020) metadata id 7d1ae3ba-9b65-49d9-b5a9-67ad6c0ee8a5",
                    "key": "7d1ae3ba-9b65-49d9-b5a9-67ad6c0ee8a5",
                    "label": "chs_1(2020) metadata",
                    "uuid": "d94bde56-bf65-5470-9ff4-cb5d94899d67",
                    "value": "10005"
                },
                {
                    "description": "Jurisdiction Metadata for Luapula Province (2020) metadata id b4d25f09-1365-41aa-ac37-f5768d9075bf",
                    "key": "b4d25f09-1365-41aa-ac37-f5768d9075bf",
                    "label": "Luapula Province (2020) metadata",
                    "uuid": "dd3f4869-106f-530c-87b5-4a40cffd89f9",
                    "value": "10001"
                },
                {
                    "description": "Jurisdiction Metadata for Nchelenge District (2020) metadata id 7d1297d2-a7e7-4896-a391-31d14cab9d32",
                    "key": "7d1297d2-a7e7-4896-a391-31d14cab9d32",
                    "label": "Nchelenge District (2020) metadata",
                    "uuid": "a6e503e8-8127-5432-bc22-45928b4569f3",
                    "value": "10002"
                },
                {
                    "description": "Jurisdiction Metadata for Chisenga(2020) metadata id 3c518249-2441-4e02-bf76-1f9de9498e76",
                    "key": "3c518249-2441-4e02-bf76-1f9de9498e76",
                    "label": "Chisenga(2020) metadata",
                    "uuid": "e89f5f87-2bcc-54c0-846e-1a08c8098b86",
                    "value": "10003"
                }
            ],
            "type": "SettingConfiguration"
        }
    ]
}
```

@dubdabasoduba @Rkareko ^^ is a sample payload of what we send - literally what Richard had posted above, but with more entries.

We don't have `locationId` but we have `_id`, `identifier`, and `uuid` for each settings entry.  Hopefully taken together these can work?  That is, would it be possible to use `_id`, `identifier`, and `uuid` to identify the specific entry to delete?

**Comment by dubdabasoduba** [comment]
> ```json
> {
>     "settingConfigurations": [
>         {
>             "_id": "fc17ac3e-ffea-55d4-902c-3069d675c198",
>             "identifier": "jurisdiction_metadata-population",
>             "settings": [
>                 {
>                     "description": "Jurisdiction Metadata for chs_1(2020) metadata id 7d1ae3ba-9b65-49d9-b5a9-67ad6c0ee8a5",
>                     "key": "7d1ae3ba-9b65-49d9-b5a9-67ad6c0ee8a5",
>                     "label": "chs_1(2020) metadata",
>                     "uuid": "d94bde56-bf65-5470-9ff4-cb5d94899d67",
>                     "value": "10005"
>                 },
>                 {
>                     "description": "Jurisdiction Metadata for Luapula Province (2020) metadata id b4d25f09-1365-41aa-ac37-f5768d9075bf",
>                     "key": "b4d25f09-1365-41aa-ac37-f5768d9075bf",
>                     "label": "Luapula Province (2020) metadata",
>                     "uuid": "dd3f4869-106f-530c-87b5-4a40cffd89f9",
>                     "value": "10001"
>                 },
>                 {
>                     "description": "Jurisdiction Metadata for Nchelenge District (2020) metadata id 7d1297d2-a7e7-4896-a391-31d14cab9d32",
>                     "key": "7d1297d2-a7e7-4896-a391-31d14cab9d32",
>                     "label": "Nchelenge District (2020) metadata",
>                     "uuid": "a6e503e8-8127-5432-bc22-45928b4569f3",
>                     "value": "10002"
>                 },
>                 {
>                     "description": "Jurisdiction Metadata for Chisenga(2020) metadata id 3c518249-2441-4e02-bf76-1f9de9498e76",
>                     "key": "3c518249-2441-4e02-bf76-1f9de9498e76",
>                     "label": "Chisenga(2020) metadata",
>                     "uuid": "e89f5f87-2bcc-54c0-846e-1a08c8098b86",
>                     "value": "10003"
>                 }
>             ],
>             "type": "SettingConfiguration"
>         }
>     ]
> }
> ```
> 
> @dubdabasoduba @Rkareko ^^ is a sample payload of what we send - literally what Richard had posted above, but with more entries.
> 
> We don't have `locationId` but we have `_id`, `identifier`, `key`, and `uuid` for each settings entry. Hopefully taken together these can work? That is, would it be possible to use `_id`, `identifier`, and `uuid`/`key` to identify the specific entry to delete?

@Rkareko I think you can make the `locationId` parameter optional and only used when we have the location otherwise the `identifier` & `key` will work.

**Comment by Rkareko** [comment]
@rehammuzzamil Is there anything that needs further clarification on this issue?

**Comment by rehammuzzamil** [comment]
Thanks @Rkareko . Looks good so far! I will start the implementation then.

The conclusion from the above discussion:

- [ ] We need to ignore saving records where the `value` field is blank
- [ ] We also need to provide support of deleting existing metadata entries where the value field is empty. To delete record entries, a combination of identifier, key, and locationId (optional) will be used.

Please correct me if there is anything wrong.

**Comment by Rkareko** [comment]
> Thanks @Rkareko . Looks good so far! I will start the implementation then.
> 
> The conclusion from the above discussion:
> 
> * [ ]  We need to ignore saving records where the `value` field is blank
> * [ ]  We also need to provide support of deleting existing metadata entries where the value field is empty. To delete record entries, a combination of identifier, key, and locationId (optional) will be used.
> 
> Please correct me if there is anything wrong.

@rehammuzzamil this is correct.
@dubdabasoduba @moshthepitt @ciremusyoka any corrections or additions to this?

**Comment by rehammuzzamil** [comment]
During the implementation, I have figured out a few cases, please share your thoughts on this @dubdabasoduba  @moshthepitt 

1- I think we might not require the deletion of entries for new records since we are limiting the persistence of records where the `value` field is blank and the identifier starts with` jurisdiction_metadata.` It would be sufficient enough to handle new entries with a blank value.
2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
@Rkareko Please let me know if there is anything incorrect.
Thanks!

**Comment by Rkareko** [comment]
> 1- I think we might not require the deletion of entries for new records since we are limiting the persistence of records where the value field is blank and the identifier starts with jurisdiction_metadata. It would be sufficient enough to handle new entries with a blank value. 

This is correct

**Comment by Rkareko** [comment]
> 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
@Rkareko Please let me know if there is anything incorrect.

@rehammuzzamil The main usecase for this issue is to provide a way for the users of the API  to delete existing jurisdiction metadata. The ask from the FE team was to trigger deletion of existing jurisdiction metadata (determined by using identifier, key, and locationId (optional) combination similar to the uploaded settings payload) when a settings payload with a blank `value` field is uploaded.

**Comment by rehammuzzamil** [comment]
> > 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
> > @Rkareko Please let me know if there is anything incorrect.
> 
> @rehammuzzamil The main usecase for this issue is to provide a way for the users of the API to delete existing jurisdiction metadata. The ask from the FE team was to trigger deletion of existing jurisdiction metadata (determined by using identifier, key, and locationId (optional) combination similar to the uploaded settings payload) when a settings payload with a blank `value` field is uploaded.

@Rkareko Is this related to the same end-point shared above or do we need to expose a separate end-point for deletion of records? Also, please confirm what do we mean by jurisdiction_metadata (I assume here we are referring to settings_metadata where identifier starts with `jurisdiction_metadata`).

**Comment by moshthepitt** [comment]
>  Is this related to the same end-point shared above or do we need to expose a separate end-point for deletion of records? Also, please confirm what do we mean by jurisdiction_metadata (I assume here we are referring to settings_metadata where identifier starts with jurisdiction_metadata).

@rehammuzzamil the hope is that we can use the same endpoint to make for an easier UI/UX.

Users upload these "jurisdiction metadata" via CSV upload from somewhere like https://web.reveal-stage.smartregister.org/jurisdiction-metadata but they don't have a way to delete them, because the UI is only a CSV upload/downnload button so this change allows them to specify in the CSV itself which records should be deleted if their exist.

**Comment by Rkareko** [comment]
> > > 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
> > > @Rkareko Please let me know if there is anything incorrect.
> > 
> > 
> > @rehammuzzamil The main usecase for this issue is to provide a way for the users of the API to delete existing jurisdiction metadata. The ask from the FE team was to trigger deletion of existing jurisdiction metadata (determined by using identifier, key, and locationId (optional) combination similar to the uploaded settings payload) when a settings payload with a blank `value` field is uploaded.
> 
> @Rkareko Is this related to the same end-point shared above or do we need to expose a separate end-point for deletion of records? Also, please confirm what do we mean by jurisdiction_metadata (I assume here we are referring to settings_metadata where identifier starts with `jurisdiction_metadata`).

@rehammuzzamil this is the same endpoint.
Jurisdiction metadata is settings_metadata where identifier starts with jurisdiction_metadata.

**Comment by rehammuzzamil** [comment]
> > Is this related to the same end-point shared above or do we need to expose a separate end-point for deletion of records? Also, please confirm what do we mean by jurisdiction_metadata (I assume here we are referring to settings_metadata where identifier starts with jurisdiction_metadata).
> 
> @rehammuzzamil the hope is that we can use the same endpoint to make for an easier UI/UX.
> 
> Users upload these "jurisdiction metadata" via CSV upload from somewhere like https://web.reveal-stage.smartregister.org/jurisdiction-metadata but they don't have a way to delete them, because the UI is only a CSV upload/downnload button so this change allows them to specify in the CSV itself which records should be deleted if their exist.

That makes sense @moshthepitt . I have provided support for the deletion of records where the value is empty against the given identifier. Can you please confirm that is there a use case to delete some specific records or only those records where the identifier starts with `jurisdiction_metadata` and the value field is empty? If this is the only case, I have added a check to delete all these records which meet such criteria, whenever the API is triggered again (UPDATE) and it works fine.
cc : @Rkareko

**Comment by Rkareko** [comment]
> > > Is this related to the same end-point shared above or do we need to expose a separate end-point for deletion of records? Also, please confirm what do we mean by jurisdiction_metadata (I assume here we are referring to settings_metadata where identifier starts with jurisdiction_metadata).
> > 
> > 
> > @rehammuzzamil the hope is that we can use the same endpoint to make for an easier UI/UX.
> > Users upload these "jurisdiction metadata" via CSV upload from somewhere like https://web.reveal-stage.smartregister.org/jurisdiction-metadata but they don't have a way to delete them, because the UI is only a CSV upload/downnload button so this change allows them to specify in the CSV itself which records should be deleted if their exist.
> 
> That makes sense @moshthepitt . I have provided support for the deletion of records where the value is empty against the given identifier. Can you please confirm that is there a use case to delete some specific records or only those records where the identifier starts with `jurisdiction_metadata` and the value field is empty? If this is the only case, I have added a check to delete all these records which meet such criteria, whenever the API is triggered again (UPDATE) and it works fine.
> cc : @Rkareko

@rehammuzzamil confirm whether this scenario has been covered

1.  Upload a jurisdiction_metadata settings payload sample below
```
{
  settingConfigurations:
    [
      {
        "_id": "109efe73-cf30-5025-82ee-4b9d436446a4",
        "identifier": "jurisdiction_metadata-structures",
        "settings": [
          {
            "description": "Jurisdiction Metadata for Siachitema id 453b01db-ab9e-4ad9-8300-0b6641529ac9",
            "key": "453b01db-ab9e-4ad9-8300-0b6641529ac9",
            "label": "Siachitema",
            "uuid": "1f5ead08-4b2c-5888-98cb-98858bea371d",
            "value": "200"
          }
        ],
        "type": "SettingConfiguration"
      },
    ]
}
```
2. To delete the the setting metadata record created by the API call on #1 above, the user sends the same payload but this time the `value`  field is empty. Sample below 
```
{
  settingConfigurations:
    [
      {
        "_id": "109efe73-cf30-5025-82ee-4b9d436446a4",
        "identifier": "jurisdiction_metadata-structures",
        "settings": [
          {
            "description": "Jurisdiction Metadata for Siachitema id 453b01db-ab9e-4ad9-8300-0b6641529ac9",
            "key": "453b01db-ab9e-4ad9-8300-0b6641529ac9",
            "label": "Siachitema",
            "uuid": "1f5ead08-4b2c-5888-98cb-98858bea371d",
            "value": ""
          }
        ],
        "type": "SettingConfiguration"
      },
    ]
}
```
3. The settings metadata record in #1 has been deleted from the database

**Comment by rehammuzzamil** [comment]
Sure @Rkareko , Let me test.
Thanks!

**Comment by dubdabasoduba** [comment]
> During the implementation, I have figured out a few cases, please share your thoughts on this @dubdabasoduba @moshthepitt
> 
> 1- I think we might not require the deletion of entries for new records since we are limiting the persistence of records where the `value` field is blank and the identifier starts with` jurisdiction_metadata.` It would be sufficient enough to handle new entries with a blank value.
> 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
> @Rkareko Please let me know if there is anything incorrect.
> Thanks!

- I don't think I follow. point 1 here seems to suggest blank values won't be ignored for settings with any other identifier is this the case? If so I don't think that implementation is correct. My thinking was we are to block all settings from saving blank values.

- This is also the same for the deletion this should happen for all settings and not just the jurisdiction_metadata

@Rkareko @moshthepitt do we have a scenario where we need settings with blank values?

**Comment by Rkareko** [comment]
> > During the implementation, I have figured out a few cases, please share your thoughts on this @dubdabasoduba @moshthepitt
> > 1- I think we might not require the deletion of entries for new records since we are limiting the persistence of records where the `value` field is blank and the identifier starts with` jurisdiction_metadata.` It would be sufficient enough to handle new entries with a blank value.
> > 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
> > @Rkareko Please let me know if there is anything incorrect.
> > Thanks!
> 
> * I don't think I follow. point 1 here seems to suggest blank values won't be ignored for settings with any other identifier is this the case? If so I don't think that implementation is correct. My thinking was we are to block all settings from saving blank values.
> * This is also the same for the deletion this should happen for all settings and not just the jurisdiction_metadata
> 
> @Rkareko @moshthepitt do we have a scenario where we need settings with blank values?

@dubdabasoduba cc @rehammuzzamil, @moshthepitt I agree that this should apply to all settings. It's just that the use case given concentrated on `jurisdiction_metadata` settings

I don't think there is any scenario where we need settings with blank values.

**Comment by rehammuzzamil** [comment]
> > > During the implementation, I have figured out a few cases, please share your thoughts on this @dubdabasoduba @moshthepitt
> > > 1- I think we might not require the deletion of entries for new records since we are limiting the persistence of records where the `value` field is blank and the identifier starts with` jurisdiction_metadata.` It would be sufficient enough to handle new entries with a blank value.
> > > 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
> > > @Rkareko Please let me know if there is anything incorrect.
> > > Thanks!
> > 
> > 
> > 
> > * I don't think I follow. point 1 here seems to suggest blank values won't be ignored for settings with any other identifier is this the case? If so I don't think that implementation is correct. My thinking was we are to block all settings from saving blank values.
> > * This is also the same for the deletion this should happen for all settings and not just the jurisdiction_metadata
> > 
> > @Rkareko @moshthepitt do we have a scenario where we need settings with blank values?
> 
> @dubdabasoduba cc @rehammuzzamil, @moshthepitt I agree that this should apply to all settings. It's just that the use case given concentrated on `jurisdiction_metadata` settings
> 
> I don't think there is any scenario where we need settings with blank values.

Okay noted, I will remove the check for jurisdiction_metadata and keep it generic for all.

**Comment by dubdabasoduba** [comment]
> > > > During the implementation, I have figured out a few cases, please share your thoughts on this @dubdabasoduba @moshthepitt
> > > > 1- I think we might not require the deletion of entries for new records since we are limiting the persistence of records where the `value` field is blank and the identifier starts with` jurisdiction_metadata.` It would be sufficient enough to handle new entries with a blank value.
> > > > 2- Though, we still need to delete entries having a blank value that is already added to the server. Therefore, I have provided support for it. The delete action will be triggered once CSV's (payload) is updated. Delete will search for all the metadata against the given identifier and will delete only those records which have the value field empty.  I was able to delete, correct records via identifier only. Deletion will only be performed if the settings identifier starts with jurisdiction_metadata.
> > > > @Rkareko Please let me know if there is anything incorrect.
> > > > Thanks!
> > > 
> > > 
> > > 
> > > * I don't think I follow. point 1 here seems to suggest blank values won't be ignored for settings with any other identifier is this the case? If so I don't think that implementation is correct. My thinking was we are to block all settings from saving blank values.
> > > * This is also the same for the deletion this should happen for all settings and not just the jurisdiction_metadata
> > > 
> > > @Rkareko @moshthepitt do we have a scenario where we need settings with blank values?
> > 
> > 
> > @dubdabasoduba cc @rehammuzzamil, @moshthepitt I agree that this should apply to all settings. It's just that the use case given concentrated on `jurisdiction_metadata` settings
> > I don't think there is any scenario where we need settings with blank values.
> 
> Okay noted, I will remove the check for jurisdiction_metadata and keep it generic for all.

Awesome!. Nice job on this

**Comment by rehammuzzamil** [comment]
Here is the result of testing: 
**Step 1-** Post settings configs as mentioned in [1](https://github.com/OpenSRP/opensrp-server-web/issues/772#issuecomment-799210559) above.
**Step 2-** Get Settings configs, following is retrieved:
```

[{
	"identifier": "jurisdiction_metadata-structures",
	"settings": [{
		"settingMetadataId": "19",
		"serverVersion": 0,
		"description": "Jurisdiction Metadata for Siachitema id 453b01db-ab9e-4ad9-8300-0b6641529ac9",
		"label": "Siachitema",
		"type": "Setting",
		"value": "200",
		"uuid": "1f5ead08-4b2c-5888-98cb-98858bea371d",
		"key": "453b01db-ab9e-4ad9-8300-0b6641529ac9",
		"settingIdentifier": "jurisdiction_metadata-structures"
	}],
	"serverVersion": 1551439200283,
	"_rev": "v1",
	"_id": "109efe73-cf30-5025-82ee-4b9d436446a4",
	"type": "SettingConfiguration"
}]
```

**Step 3-** Post settings configs as mentioned in [2](https://github.com/OpenSRP/opensrp-server-web/issues/772#issuecomment-799210559) above.

**Step 4-** Get settings configs, It is observed that the setting posted in 1 is deleted.
` []`

@Rkareko
