### ISSUE TITLE
Team assignment should expire on plan status change to Complete or Retired

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#792]
See original discussion issue: https://github.com/OpenSRP/web/issues/538.

Team assignment should expire on plan end date (current implementation) as well as when plan status changes to Complete or Retired.

This issue will be picked up after training data set for ANC is completed.

LOE - 2 days, will be picked up around April 5th

**Comment by rehammuzzamil** [comment]
As per my understanding, the API `/rest/organization/assignLocationsAndPlans` is used for the team assignment.
In this API, teams are assigned to the location and plans and wrt the implementation, an entry is made into the `team.organization_location` table. Once we change the plan status to **Retired or Completed** we need to expire the team assignment in the Plan `PUT` API. Team assignment can be expired in the following ways:

- We can remove the entry of the team assignment from the table.
- Or we can update the entry by updating the `to_date` field. 

 @bennsimon  @dubdabasoduba Can you please confirm what's the best way to deal with this?
cc : @cafootitt

**Comment by dubdabasoduba** [comment]
> As per my understanding, the API `/rest/organization/assignLocationsAndPlans` is used for the team assignment.
> In this API, teams are assigned to the location and plans and wrt the implementation, an entry is made into the `team.organization_location` table. Once we change the plan status to **Retired or Completed** we need to expire the team assignment in the Plan `PUT` API. Team assignment can be expired in the following ways:
> 
> * We can remove the entry of the team assignment from the table.
> * Or we can update the entry by updating the `to_date` field.
> 
> @bennsimon @dubdabasoduba @Rkareko Can you please confirm what's the best way to deal with this?
> cc : @cafootitt

@rehammuzzamil what happens when the `to_date` is added? Does the assignment not sure? I haven't tested this to check. 
I am okay with updating the assignment with a `PUT` to either change the `to_date` or delete the whole row

**Comment by rehammuzzamil** [comment]
> > As per my understanding, the API `/rest/organization/assignLocationsAndPlans` is used for the team assignment.
> > In this API, teams are assigned to the location and plans and wrt the implementation, an entry is made into the `team.organization_location` table. Once we change the plan status to **Retired or Completed** we need to expire the team assignment in the Plan `PUT` API. Team assignment can be expired in the following ways:
> > 
> > * We can remove the entry of the team assignment from the table.
> > * Or we can update the entry by updating the `to_date` field.
> > 
> > @bennsimon @dubdabasoduba @Rkareko Can you please confirm what's the best way to deal with this?
> > cc : @cafootitt
> 
> @rehammuzzamil what happens when the `to_date` is added? Does the assignment not sure? I haven't tested this to check.
> I am okay with updating the assignment with a `PUT` to either change the `to_date` or delete the whole row

@dubdabasoduba I believe as per the current workflow team assignment is expired on the basis of the `to_date` field. I believe this is the approach followed in **Reveal** @Rkareko is it correct? I think we can expire the team assignment by modifying the `to_date` field to the triggering date of changing plan status to Retired/Completed minus 1 day. But this is a bit unclear to me as I was unable to test the flow,
If deleting the whole row is okay from the perspective of implementation. I think we can go with this approach.

**Comment by Rkareko** [comment]
@rehammuzzamil @dubdabasoduba , I think we can follow the approach used by the Web UI when revoking team assignments which is done by updating the `to_date`  to current date minus 1. @p-netm Can confirm the approach used.

> @dubdabasoduba I believe as per the current workflow team assignment is expired on the basis of the to_date field. I believe this is the approach followed in Reveal @Rkareko is it correct? I think we can expire the team assignment by modifying the to_date field to the triggering date of changing plan status to Retired/Completed minus 1 day. But this is a bit unclear to me as I was unable to test the flow,
If deleting the whole row is okay from the perspective of implementation. I think we can go with this approach.

**Comment by p-netm** [comment]
> @rehammuzzamil @dubdabasoduba , I think we can follow the approach used by the Web UI when revoking team assignments which is done by updating the `to_date` to current date minus 1. @p-netm Can confirm the approach used.
> 
> > @dubdabasoduba I believe as per the current workflow team assignment is expired on the basis of the to_date field. I believe this is the approach followed in Reveal @Rkareko is it correct? I think we can expire the team assignment by modifying the to_date field to the triggering date of changing plan status to Retired/Completed minus 1 day. But this is a bit unclear to me as I was unable to test the flow,
> > If deleting the whole row is okay from the perspective of implementation. I think we can go with this approach.

we set the end date to the current date from the web, remember we had an issue in reveal where setting the end date to a past date would prevent re-doing the exact assignment on the same day.

**Comment by dubdabasoduba** [comment]
> @rehammuzzamil @dubdabasoduba , I think we can follow the approach used by the Web UI when revoking team assignments which is done by updating the `to_date` to current date minus 1. @p-netm Can confirm the approach used.
> 
> > @dubdabasoduba I believe as per the current workflow team assignment is expired on the basis of the to_date field. I believe this is the approach followed in Reveal @Rkareko is it correct? I think we can expire the team assignment by modifying the to_date field to the triggering date of changing plan status to Retired/Completed minus 1 day. But this is a bit unclear to me as I was unable to test the flow,
> > If deleting the whole row is okay from the perspective of implementation. I think we can go with this approach.

Agreed

**Comment by rehammuzzamil** [comment]
> > @rehammuzzamil @dubdabasoduba , I think we can follow the approach used by the Web UI when revoking team assignments which is done by updating the `to_date` to current date minus 1. @p-netm Can confirm the approach used.
> > > @dubdabasoduba I believe as per the current workflow team assignment is expired on the basis of the to_date field. I believe this is the approach followed in Reveal @Rkareko is it correct? I think we can expire the team assignment by modifying the to_date field to the triggering date of changing plan status to Retired/Completed minus 1 day. But this is a bit unclear to me as I was unable to test the flow,
> > > If deleting the whole row is okay from the perspective of implementation. I think we can go with this approach.
> 
> we set the end date to the current date from the web, remember we had an issue in reveal where setting the end date to a past date would prevent re-doing the exact assignment on the same day.

I think then we can update the `to_date` field to the current date.
@Rkareko  @dubdabasoduba does it sounds okay?

**Comment by rehammuzzamil** [comment]
Teams are unassigned when the plan status changes to RETIRED or COMPLETED through PUT api.
Here are few scenarios for acceptance criteria:

- If there is no assigned team found against the given plan identifier, it would not impact the current workflow and it would simply alter the status only (as per the current PUT API behavior).
- If there are multiple team assignments found against a given plan identifier, all team assignments will be revoked (by updating the to_date param to the current date)

cc: @samkanga  @p-netm

**Comment by samkanga** [comment]
This passed QA.
