### ISSUE TITLE
Blood Screening Tasks not being generated for an existing household in a case-triggered plan

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-server-web#812]
https://smartregister.atlassian.net/browse/RVL-1575
Plan: A1 - เมืองทอง(Site)-1 - Test1 อภิรังษีกุล - 2021-04-26 - Site
Plan ID: `89932189-8b22-44d3-8f9a-0ef72cc0fab2`

Link: Reveal Web Preview

User: test77

For existing structures with household members registered no blood screening tasks generated when a new plan is generated. See sample screenshot below:

![image](https://user-images.githubusercontent.com/5908630/116112880-ab221000-a6c0-11eb-8c4a-e2eca74b2b3e.png)

**Comment by Rkareko** [comment]
@LZRS we also need to run [this script](https://gist.github.com/Andati/41932629437f8cf7cd3978ce62842480) to update existing client records with location ids

**Comment by Naima-Bashir** [comment]
How to test this: 
1. Create two case triggered plans
2. Then a routine plan
3. register family members in plan A
4. Create a new plan for the same location
5. Check if the old family have blood screening

**Comment by Naima-Bashir** [comment]
The bug is still existent for families that are already in the plans. 
The blood screening tasks works for new structures and new families but fails on existing families. 
Here is a screenshot. 
![Uploading image.png…]()

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/122008140-58f89380-cdc1-11eb-8917-d2d7049b3271.png)
user: raitest
OA- Site 1
Plan- Task 3

**Comment by Naima-Bashir** [comment]
Passed QA from client side
