### ISSUE TITLE
Perform Checks on API for Tasks Generation

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#828]
There was an instance where NiFi generated a huge number of tasks for two plans on the Thailand production instance. This ticket seeks to create a check through the OpenSRP API on whether a task exist in the OpenSRP DB for an entity before generating additional tasks for it. This check is to ensure that no duplicate tasks are generated.

Acceptance Criteria
1. Create a new task on the server by making a POST request to `{server url}/opensrp/rest/task/` with a sample payload as shown below
```
{
    "for": "52c0c62e-ac5a-46b9-a326-72bb5ec4c010",
    "code": "Blood Screening",
    "focus": "a9b8e724-be9f-11eb-8529-0242ac130003",
    "owner": "thai1",
    "status": "Ready",
    "priority": "routine",
    "requester": "thai1",
    "authoredOn": "2021-02-08T14:12:43.352+02:00",
    "identifier": "b3bf7fd0-be9f-11eb-8529-0242ac130003",
    "syncStatus": "Created",
    "description": "Visit all residential structures (100%) within a 1 km radius of a confirmed index case and test each registered person",
    "structureId": "be945430-be9f-11eb-8529-0242ac130003",
    "lastModified": "2021-02-08T14:12:43.353+02:00",
    "serverVersion": 1599117862865,
    "businessStatus": "Not Visited",
    "planIdentifier": "cb36fa26-be9f-11eb-8529-0242ac130003",
    "executionPeriod": {
        "end": "2021-02-10T00:00:00.000+02:00",
        "start": "2021-02-03T00:00:00.000+02:00"
    },
    "groupIdentifier": "d6e4bd7c-be9f-11eb-8529-0242ac130003"
}
```
2. Confirm that the task has been created by making a GET request to `{server url}/opensrp/rest/task/{identifier}` 
3. Create a new task by changing the `identifier` for the task in step #1 and any other fields except the following :-
a) `planIdentifier`
b) `groupIdentifier`
c) `code`
d) `for`
4. POST the new task JSON from step 3 to the server as was done in step 1
5. Retrieve the new task from step 3 by making a GET request to `{server url}/opensrp/rest/task/{identifier}`. NB use the new identifier from step 3

Expected outcome
Step 5 should not return a task.
The server should prevent generation of duplicate tasks. Duplicate tasks are defined as having the same combination of the following properties  :- `planIdentifier` + `groupIdentifier` + `code` + `for`

**Comment by Naima-Bashir** [comment]
the GET should return error 400 when the task doesn't exist,
for the POST we'll remove the field priority , seems to be the issue

**Comment by Naima-Bashir** [comment]
step1:
![image](https://user-images.githubusercontent.com/61143692/121639928-ecfeee00-ca95-11eb-9472-403bfcfada71.png)

step 2: 
![image](https://user-images.githubusercontent.com/61143692/121640095-29cae500-ca96-11eb-9904-469c090c43fa.png)

step 3: with a new id 
![image](https://user-images.githubusercontent.com/61143692/121640246-5a128380-ca96-11eb-9869-2fbc3af42766.png)

step 5:  it returned error 400 for the new id
![image](https://user-images.githubusercontent.com/61143692/121640388-87f7c800-ca96-11eb-9345-6cc2bd9390cb.png)
