### ISSUE TITLE
Changes to the product-catalogue endpoint

### ISSUE THREAD

**Issue by Wambere** [opensrp/opensrp-server-web#841]
Requesting the following changes to this endpoint 

### 1. Allow passing serverVersion of 0
**Current behaviour:** Hitting the endpoint `/opensrp/rest/product-catalogue?serverVersion=0` returns the error `400 Bad Request`
**Expected behaviour:** Hitting the endpoint returns all records with serverVersions greater than 0

### 2. Order of records returned
**Current behaviour:** The records returned are not in order
**Expected behaviour:** Monotonically increasing serverVersions. For example (1, 2, 3, 13, 14, 27) is acceptable, but (1, 3, 2, 27, 14) is not acceptable

### 3. Add limit parameter to endpoint
**Current Behaviour:** Adding the parameter `limit=10` does not affect the number of records returned
**Expected Behaviour:** Adding the parameter `limit=10` returns only 10 records

**Comment by hilpitome** [comment]
@Wambere this change has been made and snapshot (2.8.5-SNAPSHOT) deployed to sonatype

**Comment by Wambere** [comment]
Hi @hilpitome, thanks for the update.
I did a quick pass on the endpoint and noticed that passing the `serverVersion` parameter alone works as expected, passing the `serverVersion` and the `limit` parameter together also works as expected. But passing the `limit` parameter alone still returns everything - ignoring the limit. Is this something that can be checked?

**Comment by hilpitome** [comment]
@Wambere yes, that can be checked
