### ISSUE TITLE
Changes to the location-tag endpoint

### ISSUE THREAD

**Issue by Wambere** [opensrp/opensrp-server-web#843]
Requesting the following changes to this endpoint so that we can hook it up to the Beam pipeline 

### 1. Add serverVersions to items
**Current behaviour:** Returned items do not have serverVersions
**Expected behaviour:** Returned items should have serverVersions

### 2. Add serverVersion parameter to endpoint
**Current behaviour:** Endpoint does not support this parameter
**Expected behaviour:** I should be able to filter results using this parameter. For example `location-tag?serverVersion=0` should return all records with serverVersions greater than 0

### 3. Add limit parameter to endpoint 
**Current behaviour:** Endpoint does not support this parameter
**Expected behaviour:** I should be able to filter results using this parameter. For example `location-tag?limit=10` should return only 10 records

### 4. Confirm order of records returned
**Current behaviour:** There are only 4 records and they don't have serverVersions so I can't be sure
**Expected behaviour:** Monotonically increasing serverVersions. For example (1, 2, 3, 13, 14, 27) is acceptable, but (1, 3, 2, 27, 14) is not acceptable

**Comment by msschroeder** [comment]
@Wambere I chatted with the data analyst. We are okay with the uploading the names of the location tags. Should I close this issue still or is this work that will be done much later and we should just leave it open?

**Comment by Wambere** [comment]
closing as this is not needed any more
