### ISSUE TITLE
New Endpoint Feature Request: request for only certain fields

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-server-web#85]
I sit possible to add a way to request only certain fields from the plans endpoint?  Specifically, this:

1. Add a way to request for only certain plan fields.  Immediately would want to query only for plan identifiers so that we can be certain the plan identifier that the Reveal web app (or any other thing) has generated is unique.
2. Add a way to get only action/goal ids from plans, to achieve the same thing as the above.

**Comment by githengi** [comment]
@moshthepitt so this should  return Ids for plans, actions and/or goals depending the parameters passed ?

Also we should only allow querying actions and/or goals when one has provided the plan id

**Comment by moshthepitt** [comment]
@githengi 

> @moshthepitt so this should return Ids for plans, actions and/or goals depending the parameters passed ?

Yes

> Also we should only allow querying actions and/or goals when one has provided the plan id

Yes!!

---

Also, is there a way to make this generic so that the same can be achieved for other endpoints like tasks, jurisdictions, clients, etc?

**Comment by githengi** [comment]
@moshthepitt how do you propose to make this generic?
Will one will be providing  the list of fields that they want returned?

**Comment by moshthepitt** [comment]
> @moshthepitt how do you propose to make this generic?
Will one will be providing the list of fields that they want returned?

@githengi I think that could work.  For example, on onadata on the data endpoint they have a parameter called `fields` which is optional and expects a list of fields which you want returned.
