### ISSUE TITLE
Tasks Not Generated for Plan on Thailand Preview

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#882]
Tasks generation on Thailand Preview takes place in OpenSRP. Cases have been reported where an active case triggered plans failed to generate tasks. The plan IDs for these are:

- [x] `f0926402-f8f2-4ab6-9264-d8348c4d8387`                 name = `A1-เมืองทอง(Site)-1- สมคิด_ อภิรังษีกุล-2021-06-23-Site`
- [x]  `ad0d6be5-d9a8-47d4-b6fb-e669661518b2`              name = `A1-เมืองทอง(Source)-1- สมคิด_ อภิรังษีกุล-2021-06-23-Source`
- [x] `aa69b2d6-b5ce-4a4d-8913-a7b659f5e883   `            name = `A1-เมืองทอง(Source)-1- สมคิด_ อภิรังษีกุล-2021-06-23-Source`

**Comment by madrinekariuki** [comment]
@Rkareko 
This seems to be working now.
see below test details, steps and results.
I have tested using 
plan ID 19edb644-c073-4545-8a7e-b9ce0ac46245
plan name A1 - Muangthong(Site)-8 - Chester Arthur - 2021-07-05 - Site

Thai preview v5.3.26
user: test77

Steps
-logged into the app.
-opened the plan 
- created a new residential structure(Geret Family) with 2 members.

![image](https://user-images.githubusercontent.com/84722169/124484992-c42bf900-ddb4-11eb-901d-630020f44358.png)

- Added details of the family and tasks were generated.
- I filled in the details of the family members.
![image](https://user-images.githubusercontent.com/84722169/124485103-e7ef3f00-ddb4-11eb-9c20-2c01ce1ad4ef.png)

- From the Web UI the details also reflected.
-
![image](https://user-images.githubusercontent.com/84722169/124485416-33a1e880-ddb5-11eb-9148-899a58c85353.png)


Results:
We can see tasks are being generated and we will proceed to close this item
