### ISSUE TITLE
Deletion of Duplicate plans on Thailand Production OpenSRP DB

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#886]
Thailand has identified a list of potential duplicate plans that need to be deleted from the Production OpenSRP DB. These are provided on the thread [here](https://dsme.slack.com/archives/GRVF5Q5T7/p1625478675004700). Please double check to confirm they are duplicate before deletion.

**Comment by LZRS** [comment]
Some of the duplicated plans are missing from our list.
@Wambere What criteria is currently used to identify duplicated plans, case triggered plans?

cc @samkanga @Rkareko

**Comment by Rkareko** [comment]
@Wambere cc @samkanga @LZRS we currently check for plans with the same `opensrpEventId`. Are there any additional checks we may need to add?

**Comment by Wambere** [comment]
A combination of case_id and flag would be best bet

**Comment by samkanga** [comment]
I will go ahead and close this ticket
