### ISSUE TITLE
Get all children and grand children of a jurisdiction

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-server-web#90]
Is it possible to add support to the `/rest/location/findByProperties` endpoint to return all the children,and grand children - basically the entire family of a jurisdiction?

For example, I would love to be able to get all the jurisdictions whose root parent is `Namibia`.

**Comment by githengi** [comment]
@moshthepitt this API should not use `/rest/location/findByProperties` since it should support accessing descendant locations of a single Location.

The API will this be expecting one 1 send a locationId

**Comment by moshthepitt** [comment]
@githengi that is ok.  However, will the endpoint that we use for this allow us to pair it with features from #85?  i.e. the ability to get children/grandchildren jurisdictions while at the same time only requesting for certain fields?

**Comment by moshthepitt** [comment]
Primarily, of course, we dont want to always get the geo data as it is large

**Comment by githengi** [comment]
@moshthepitt on this issue we shall only implement allowing one to omit geometry

**Comment by moshthepitt** [comment]
@githengi sawa, lets see how that ends up looking and working like
