### ISSUE TITLE
Request to Delete Duplicate Plans on Thailand Production

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#902]
CHAI has requested that we delete the following plans that have been marked as duplicate from the OpenSRP Server DB.

- [x] A1 - อูปูทะ (6305010202) - น่อหมุ วงศ์วิชุดา - 2021-07-28 - Site - Plan id: `805d4230-dfb8-4682-b96a-25e3343280fb`
- [x] A1 - อูปูทะ (6305010202) - น่อหมุ วงศ์วิชุดา - 2021-07-29 - Sitee - Plan id: `49ea1b3b-f6f8-4361-a14f-6b56c860ea1a`
- [x] A1 - ไร่รวมไทยฯ15 (6307040602) - แหง่ - - 2021-07-28 - Site - Plan id: `6103d519-4783-4404-858c-d2b7eb6840f0`
- [x] A1 - ไร่รวมไทยฯ15 (6307040602) - แหง่ - - 2021-07-29 - Site - Plan id: `919e0331-a6f2-4546-80bf-70fb39266699`

**Comment by samkanga** [comment]
@LZRS CHAI have shared additional plan IDs for deletion from the production OpenSRP DB as follows:

1. 202263bc-524f-4973-80cd-7544fd3add77
2. 0f26bb4d-e610-4e45-b5f8-1110c9f2be4e
3. 0fb96c5c-e45e-4123-ad80-727228751b72
4. 12d49f4c-6269-4d13-adaf-204b766cafe3
5. 362abc99-ca05-4956-8dbb-ad596fc68223
6. 35f1bcfd-8b26-46a3-82d8-7ef79d0a75c0
7. 345b1b0c-ea5b-4db2-865b-08c4a1d0f72a
8. 49e0f3c4-2377-409d-839e-a8781e0d1b78
9. 5788820b-ad7d-4e8c-a7a1-b4552228318d
10. 50280c4b-08c4-43fb-87a8-06667d59242b
11. 76bd5497-fd36-4c06-8961-43dad73040a5
12. 625b14d9-114e-4d33-bb54-75bc8e7d5c77
13. 61d093c7-7b6a-4ace-b824-c19f6858bbb9
14. 603f37c7-406f-4815-9489-4b52ea4956ea
15. 593205ca-f11f-4dd0-9b49-1b3cfb08a9da
16. 58ce1582-6e49-4e4d-8d0e-51053cae4efd
17. 8312eaee-82b9-47af-be90-ff482a60bd3a
18. 8803aa06-650d-4f75-a13e-8fbf7549be90
19. 8a3cdd1a-b6ff-4dcc-965e-3bbe846b53e0
20. 9bf90a6e-9737-471d-8322-e03e150faf25
21. af119b7e-e541-48f9-be39-592848e52dde
22. b1bde2f0-7c7f-4ceb-b203-79b6b8a76d9f
23. b9c45eb2-9c13-4802-981e-84ff706aa38a
24. b8dc3db2-fdc8-4567-b802-31d7a3deaaaa
25. dffd126e-c546-4e9d-ac0e-44a92c6527df
26. dd6d7605-914e-4078-94e5-0f38c1b5ea9b
27. f1f563f5-b51c-4465-819d-04f5d3be1402
28. 59676f26-38c9-4baa-b8b6-6bfbf94d2a03
29. 5b895c11-02ea-4629-b215-ffa0a0ea7dff
30. a625f96b-7adf-4000-9057-0998df2e9597
31. a9400fc9-2b7b-4b7f-ba57-9efce46de4ef
32. 86360440-3b59-4c30-bec1-91496d211834
33. 93db2be0-656c-43b0-87c2-b24112ba1f89
34. 9065f0c8-2192-4e5d-90db-e192b096d2d4
35. 1a8d5104-131d-4f9a-8865-5a4bb8e9152d
36. 1862c67a-59b1-44aa-8735-236acb438dc7
37. 1927de94-cfab-4b6e-95ef-fcb5b8be43a2
38. 212892f5-4ee4-4907-9219-413c2fedf82f
39. 2a72095c-e770-4575-86e3-288a43a93615
40. 2ba215b3-ab3a-497b-bb1f-9b1e52b12f09
41. 00b3f65b-a8a7-4417-90b4-c855ca744f2d
42. 04027a3b-20f0-4a21-968e-94246a63651e
43. 163716b8-a9a1-4a2c-bc1d-131dbdc2576d
44. 1108b890-9f4b-49d6-94ce-277353a41d50
45. 0dfd9e63-6507-4514-b5fb-152b6542c453
46. 0dc711d4-530f-404e-8c4b-d23ce38a88a7
47. 380d09cb-bb4b-4048-af74-263cf9c8793d
48. 4a4345e7-28e1-4309-89ac-a475566307b8
49. 49516826-00cd-404a-9583-f5a026f9cde1
50. bf90e358-2ba4-404b-a3f3-19daba886fa1
51. b42c50e6-730b-4729-8e58-da0235ccbb5b
52. da11e5e2-179b-40c3-a60e-3ab4fd78d902
53. d8154155-e481-44c0-bd93-7dee510958d8
54. de73490d-0868-44a8-afd6-fbbd3b96dcb1
55. defc8a7f-f4fc-4dfc-b9e3-cb0f6435426d

**Comment by LZRS** [comment]
it's done
