### ISSUE TITLE
Filter out expired plans from authenticate and user-assignments API calls

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-server-web#904]
Related to https://github.com/opensrp/opensrp-client-reveal/issues/1491

We need to filter out plans whose `effectivePeriod.end` is in the past for the following end points

- [x] [Security authenticate](https://github.com/opensrp/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/controller/UserController.java#L215)
- [x] [User-assignments](https://github.com/opensrp/opensrp-server-web/blob/master/src/main/java/org/opensrp/web/rest/OrganizationResource.java#L241)

**Comment by madrinekariuki** [comment]
closed and comment updated [here](https://github.com/opensrp/opensrp-client-reveal/issues/1491#issuecomment-895832939)
