### ISSUE TITLE
Make revoking team assignments for complete or retired plans optional

### ISSUE THREAD

**Issue by Rkareko** [opensrp/opensrp-server-web#905]
EUSM introduced [functionality to revoke team assignments](https://github.com/opensrp/opensrp-server-web/releases/tag/v2.6.5-SNAPSHOT) when a plan is completed or retired. 
We need to make this configurable for implementations like Thailand that have team assignments that persist beyond the plans effective period.

- [ ] Add an optional endpoint parameter `revoke_assignments` to the plan update endpoint. The default should be true.
- [ ] Add a check on the opensrp service layer to check the flag before revoking team assignments

**Comment by LZRS** [comment]
Closed by https://github.com/opensrp/opensrp-server-web/pull/907
