### ISSUE TITLE
Events Marked as Missing on Replica3 DB

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#921]
CHAI has reported that they identified that close to 100 events that were on a previous Raplica3 export are missing from the current Replica3 export. They would like us ti investigate what may have caused the loss of the events. This has mainly affected blood screening events, even though there are other event types missing. The following events are some event IDs to the events marked as  missing.

59A75236-A1A2-4244-A6F5-00D73D38594A
13028CF0-D252-4DFD-ACFE-218CB9A99AA5
AE358D2E-D5D3-4700-A52E-249B17855C8D
493ED12D-2D7E-4B54-AE0A-3298018F20DD
EFD0EB94-E030-4140-926E-701242DCD720
B4E21997-991A-42CC-B2DA-783AEF5BA8B0
BD30C25E-9B86-4AF5-BADF-8194D5531EF9
F8D1D2B9-1BE0-4B3B-86C5-CC6A51FF3E37
1DC1ED18-2F84-40CB-A8A4-BB752048E9E0
BA330D28-65F1-4AEB-947C-DC9532187706
FDD66DEF-8F10-499C-8CD0-F1D817E21792
C2A21A76-357F-413B-9B99-CC666781B8BE
52598911-6508-49D0-BA58-FB4AB288E54E
7D3653A7-6560-45DD-9B79-36E5D46D9B2D
94BC2FF3-0B4F-4FA6-BA79-B0A835DED185
A1F4E02E-68C0-4158-A9CE-C555E97CFB3E
5E7620A0-C2CB-43AE-97DE-A1BEB63138DF
36542073-D318-4896-9849-B78EE5CE46A3
568B82A7-9966-4410-930B-F8CDC39B34E7
34707FCE-0066-4378-A0D9-F9CEE49D5166
3653197E-D8EA-44E9-A7FA-2F0FE8188EB3
5780023D-1A10-45E2-8058-550A8ED9250C
7DE0FDC8-3246-482F-82F5-761CDFE5AAD1
C9A0C965-C13B-48F8-A8BE-92C8C2A842D5
91493ACC-F28A-4C61-B0B4-AC89696674C6
6EEDC758-C835-43FE-8F32-A47CC99085E8
E8CB4B4F-D229-4A10-8018-E40AA38BA241
B5B1BA3F-DB06-4E6F-91B2-E4ADC1AA375B
C4E01897-7CE2-40C4-AE4B-0D0E9348C1AB
715E3F51-B912-425C-B2CD-5221B5E3B14A
45D89B1F-49A9-47F2-BA2A-89D292D319D4
58A5C841-DE20-4639-8E1B-7BB36D6DD72B
D3876BA5-7347-4A48-A4C2-8B755CBC18F3
87B2D920-7646-49F9-8121-AC7A29E355A4
1C06E5EA-EC61-4484-A77C-C50644653427
B068E795-C0E3-4429-9A07-46F23EAD010E
CF609DB1-E4B6-4067-B46E-74F20960BD5E
6B60C332-FAD6-4A4F-BA98-A5E09B1AB69C
13A7CA91-C055-4B38-ABCF-C8C672419342
77775349-A73F-44DA-A711-C9C4DE3D4BC1
EB455390-C13C-4A56-AC2F-E9D53CA42DCD
132F9287-6DEC-454C-98A5-79161AC1838E
50714626-0187-4C01-9B01-CD59818B6459
CC8AF117-DABF-4952-88F8-EA7AC384869D
F3D57A55-9EAE-45C9-8967-B584995FB73C
268E854F-FFB6-4851-B77A-FF13D557492B
28FCEE33-695B-44EE-B709-585947228D67
D9238848-70AE-4673-AFDB-8E19192FCA81
3E72E770-2CC6-4837-B7D3-9816E8605A69
8CCBA9E1-71E1-4286-AD1F-08D303E481B4
DAEF5F1E-9233-467B-AD63-19718AF93908
88030C11-9583-4CBE-BCED-263FA538780F
F1256F63-1DF9-4ADB-B1DD-4454D0D6E1CB
F36C1DE2-CA4B-4BE3-82A3-532E7FF94CD3
FF69491F-BFEE-469A-AD4E-E9A354488E38

**Comment by Rkareko** [comment]
@samkanga There are no events in the opensrp db with those ids. @ciremusyoka could you check whether there are any events with those ids in the canopy db?

**Comment by ciremusyoka** [comment]
@Rkareko cc @samkanga  we also don't have any events with those plan ids in canopy db.

**Comment by Rkareko** [comment]
@moshthepitt  cc @samkanga @ciremusyoka How would the ETL process handle data that has been synced into the canopy db then later on deleted on the opensrp db. Trying to figure out whether it's possible that the data at one point existed in the opensrp db and was deleted and this was cascaded to the canopy db as well.

**Comment by samkanga** [comment]
Closing this issue as it has not been possible to determine the cause of the issue. This will be reopened if the issue recurs.
