### ISSUE TITLE
Task Status for Thailand Productino not Updating Leading to blank WebUI Dashboard

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#923]
BVBD has reported that there are mismatches between the app and web UI. For example, for plan ID 4daf4c34-3f38-495f-969f-dcfc5c2dd411, they see 27 tests and BCC on the android client, but on the web UI they only see BCC event. Checks have been made that there are blood screening events on OpenSRP with the following endpoint https://servermhealth.ddc.moph.go.th/opensrp/rest/event/sync?locationId=be847cbb-576b-4d76-b9da-f59175f74dcb&serverVersion=0&limit=10000

A check on OpenSRP Server DB showed there is no complete task:
SELECT count(*) FROM raw_tasks
WHERE full_json->>'planIdentifier' = '4daf4c34-3f38-495f-969f-dcfc5c2dd411'
AND full_json->>'groupIdentifier' = 'be847cbb-576b-4d76-b9da-f59175f74dcb'
AND full_json->>'code' = 'Blood Screening'
AND full_json->>'businessStatus' = 'Complete';

This seems to be the same issue we had encountered on Thailand. Could we run a script to correct this for all affected plans?

**Comment by LZRS** [comment]
Query
```sql
WITH tasksToUpdate AS (SELECT DISTINCT task_metadata.identifier, 
	  				 				  nextVal('core.task_server_version_seq') as new_server_version
	  				  FROM core.task_metadata
	  				  INNER JOIN core.event ON event.json->'details'->>'taskIdentifier' = task_metadata.identifier
	  				  INNER JOIN core.task ON (task_metadata.task_id = task.id 
											   AND task.json->>'status' = 'Ready'
											   AND task.json->>'businessStatus' = 'Not Visited')
					  WHERE task_metadata.code = 'Blood Screening'),
	updatedTasks AS (UPDATE core.task SET server_version = tasksToUpdate.new_server_version, 
						json = (json 
							 || '{ "status": "Completed", "businessStatus": "Complete" }'::jsonb
							 || json_build_object('serverVersion', tasksToUpdate.new_server_version)::jsonb)
					 FROM tasksToUpdate
					 WHERE tasksToUpdate.identifier = task.json->>'identifier'
					 RETURNING task.* )
UPDATE core.task_metadata
SET server_version = updatedTasks.server_version
FROM updatedTasks
WHERE updatedTasks.id = task_metadata.task_id
RETURNING *;
```

**Comment by samkanga** [comment]
Closing this ticket as issue is now resolved.
