### ISSUE TITLE
when you record screening, the app does not update and still shows RECORD SCREENING." 

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-server-web#925]
This was tested for Thailand workflow on
6.0.0-RC5
User: Onatest/Amani123

Steps
login to the app
open a yellow structure or create a new household
add family member
click on the added member to record blood screening
record blood screening and save
observe how the blood screen does not change to complete
it remains as record screening. 

NOTE this is the same behavoiur for bednet distribution when you RECORD DISTRIBUTION on the same form.

![image](https://user-images.githubusercontent.com/84722169/131290708-9e25c3a0-b867-41bb-aa6a-61209a3d3acd.png)

**Comment by samkanga** [comment]
Closing this as this was descoped.
