### ISSUE TITLE
Prevent Duplication of Thailand RACD Plans

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#929]
We encountered an instance where plans were duplicated on reveal Thailand Production for Case Triggered plans. The following fixes are required to ensure that this does not not recur.

1. Update plan creation check to factor in case_number and flag
2. Prevent creation of duplicate case_details  event

**TESTING**

**Sample Case Details Event**

```
{
    "type": "Event",
    "dateCreated": "2021-06-08T10:38:04.411+07:00",
    "serverVersion": 1601985074968,
    "identifiers": {},
    "baseEntityId": "8cf6788d-5c7b-467a-99e5-987ba6adbc15",
    "locationId": "8cf6788d-5c7b-467a-99e5-987ba6adbc15",
    "eventDate": "2020-12-06T07:00:00.000+07:00",
    "eventType": "Case_Details",
    "formSubmissionId": "efd96df5-a642-452c-9cd7-58b02cdc81b6",
    "providerId": "nifi-user",
    "duration": 0,
    "obs": [],
    "entityType": "Case_Details",
    "details": {
        "id": "2206",
        "age": "23",
        "bfid": "7107060601",
        "flag": "Site",
        "species": "V",
        "surname": "-",
        "focus_id": "8cf6788d-5c7b-467a-99e5-987ba6adbc15",
        "first_name": "เช่อ",
        "focus_name": "บ้านไร่ (7107060601)",
        "case_number": "141117000006590210607170031362",
        "family_name": "เช่อ",
        "focus_reason": "Investigation",
        "focus_status": "A1",
        "house_number": "m13",
        "ep1_create_date": "2021-06-07T00:00:00.000+0000",
        "ep3_create_date": "2021-06-08T00:00:00.000+0000",
        "investigtion_date": "2020-12-06T00:00:00.000+0000",
        "case_classification": "A"
    },
    "version": 1557860282617,
    "teamId": " ",
    "_id": "19165339-6591-4e23-a142-6817c63b96bc",
    "_rev": "v1"
}
```

**Sample Blood Screening Event**

```
{
  "_id": "e16b5ae4-a186-4b78-905a-b8948eeb7fd3",
  "obs": [
    {
      "set": [],
      "values": [
        "1"
      ],
      "fieldCode": "eligiblePerson",
      "fieldType": "formsubmissionField",
      "parentCode": "",
      "fieldDataType": "text",
      "saveObsAsArray": false,
      "formSubmissionField": "eligiblePerson",
      "humanReadableValues": []
    }
  ],
  "_rev": "v1",
  "team": "raitest",
  "type": "Event",
  "teamId": "a3bf8a41-3753-4b1d-816b-3999a30250c9",
  "details": {
    "taskStatus": "READY",
    "location_id": "eb3855da-c302-435b-b85e-2bef522d5d78",
    "form_version": "0.0.1",
    "locationUUID": "ce870295-b803-4185-a3af-719ea4c4b008",
    "appVersionName": "5.3.2",
    "planIdentifier": "daa88a0b-a0e0-4a53-a0d6-36366781eac3",
    "taskIdentifier": "f28b33db-5034-40f7-a70b-3978e472b413",
    "locationVersion": "0",
    "taskBusinessStatus": "Not Visited"
  },
  "version": 1604042574985,
  "duration": 0,
  "eventDate": "2020-10-30T00:00:00.000+07:00",
  "eventType": "blood_screening",
  "entityType": "ec_family_member",
  "locationId": "48cd7455-a6fb-40df-8bfe-43250f37cc16",
  "providerId": "raitest",
  "dateCreated": "2021-06-30T10:53:07.138+07:00",
  "identifiers": {},
  "baseEntityId": "538bbbdc-796d-47d6-b939-c14facb6bd47",
  "serverVersion": 1607066371611,
  "formSubmissionId": "718291a1-cafd-4a15-a008-20034270a87a"
}

```

**How to Add an event via the API**

Make a post request to `{baseUrl}/opensrp/rest/event/add` with a payload in the following format. The event goes into the `events` Array

```
{
  "clients": [

  ],
  "events": [
    
    ]
}
```

**How to retrieve an event from the API using the id**
Make a GET request to `{base_url}/opensrp/rest/event/sync?baseEntityId={baseEntityIdValue}` . 

`How to generate a UUID`
Use the [Online UUID Generator](https://www.uuidgenerator.net/)

**TESTS**

**A.  Test that it's possible to add any other type of event via the API**
1. Replace the `_id`, `formSubmissionId` and `baseEntityId` values in the Sample blood screening events with generated UUIds
2. Fetch the event from the API using the generated id. There should be no event returned.
2. Add the event via the API
3. Retrieve the event via the api. You should get the event.

**B. Test that it's possible to add a case details event**
1. Replace the `_id`,  `formSubmissionId`, `baseEntityId` and `details.case_number`  with randomly generated UUIdS. The `details.flag` value should remain as `Site` . Replace  any other values as you wish.
2. Fetch the event from the API using the generated id. There should be no event returned.
2. Add the event via the API
3. Retrieve the event via the API. You should get the event.

**C. Test that it's not possible to add a case details event with the same case number and flag values**
1. Replace the `_id`, `baseEntityId` and `formSubmissionId` with randomly generated UUId In the case details event used in test B. The `details.flag` and `details.case_number` values should remain the same. Replace  any other values as you wish.
2. Fetch the event from the API using the generated id. There should be no event returned.
2. Add the event via the API.
3. Retrieve the event via the API. You should not get an event.

**D. Test that it's  possible to add a case details event with the same case number but different flag value**
1. Replace the `_id`, `baseEntityId` and `formSubmissionId` with randomly generated UUIdS  in the event used in test B. The `details.flag` value should be set to `Source` .  The `details.id` and `details.case_number` should remain as is .Replace  any other values as you wish.
2. Fetch the event from the API using the generated id. There should be no event returned.
2. Add the event via the API
3. Retrieve the event via the API. You should get the event.

**Comment by madrinekariuki** [comment]
@LZRS @Rkareko @samkanga 
This has been tested by following above steps on Thai-preview
Noted that all the scenarios A-D have passed and duplicate plans are not being created.
