### ISSUE TITLE
[OpenSRP Web Related] Create an endpoint that allows querying of team assignment using the practitioner Id 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-server-web#936]
**Context**
- We would like to fetch all the teams that a practitioner is assigned to. 
- Currently, we do not have a way to fetch this but we have a way to get all the teams an authenticated user is assigned to. 
- We would like to adapt this functionality and create an endpoint that would accept the practitioner identifier as the param then fetches all the teams a practitioner is assigned to. 

**Technical Implementation**
- [ ] Have an endpoint named `/by-practitioner/{practitioner-identifier}`
- [ ] Adapt some of the work on the [`/user-assignment`](https://github.com/opensrp/opensrp-server-web/blob/e3954e08a381f6fb256b129155c980ab8ecc6455/src/main/java/org/opensrp/web/rest/OrganizationResource.java#L217) endpoint to create an endpoint with the name above. This endpoint should perform the following functions
    - [ ] Accept the `practitioner-identitier` as a required param
    - [ ] Search for all the teams that the practitioner is assigned to
    - [ ] Returns all the teams a practitioner is assigned to in a JSON Array 

**Acceptance Criteria**
- Availability of a `/by-practitioner/{practitioner-identifier}` endpoint
- Makes sure the `practitioner-identifier` is a required param on the endpoint mentioned above. 
- Return a correct list of teams a practitioner is assigned to.

**Comment by rehammuzzamil** [comment]
@dubdabasoduba Do we only need to return` List<Organization>` i.e. list of teams to which the Practitioner is assigned to?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba Do we only need to return` List<Organization>` i.e. list of teams to which the Practitioner is assigned to?

@rehammuzzamil Yes.

**Comment by rehammuzzamil** [comment]
As per our discussion @dubdabasoduba 
Here is the sample response payload of the end-point:
```

[
    {
        "id": 1,
        "identifier": "fcc19470-d599-11e9-bb65-2a2ae2dbcce4",
        "active": true,
        "name": "The Luang",
        "type": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                    "code": "team",
                    "display": "Team"
                }
            ]
        }
    }
]
```

cc : @f-odhiambo
