### ISSUE TITLE
Delete Duplicate BCC Task on Thailand Production Plan

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#943]
The plan with ID `eeb876ca-dccf-5079-bb78-f4403fdb2d51` on Thailand production generated two BCC tasks. Let's delete one of the tasks as we monitor if the issue re-occurs.

**Comment by LZRS** [comment]
The plan `eeb876ca-dccf-5079-bb78-f4403fdb2d51` had two BCC tasks with identifiers `0bb355a5-1682-4222-969f-be45e8eeb217` and `1eaf0738-0863-41fd-ae9c-3fc4ebb1a60e`. Only `1eaf0738-0863-41fd-ae9c-3fc4ebb1a60e` had an event, and opted to delete `0bb355a5-1682-4222-969f-be45e8eeb217`.

```sql
DELETE FROM core.task_metadata WHERE identifier = '0bb355a5-1682-4222-969f-be45e8eeb217';
```

```sql
DELETE FROM core.task WHERE json->>'identifier' = '0bb355a5-1682-4222-969f-be45e8eeb217';
```
