### ISSUE TITLE
Windows Users Unable to Download csv files from Reveal Web

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#951]
Windows users are experiencing an error `400` when trying to GET the url `https://reveal-sz.smartregister.org/opensrp/multimedia/media/0f9673fa-23b1-4107-9dbe-649551f6d242?dynamic-media-directory=true` in downloading the uploaded csv files from the Eswatini Reveal Web. Below is a screenshot of the error encountered:

![image](https://user-images.githubusercontent.com/5908630/134304439-d182aa16-0b92-49bf-a8cb-fc85f4a4e8fa.png)

**Comment by Rkareko** [comment]
@madrinekariuki Test both upload and download of CSV files on Window system

**Comment by madrinekariuki** [comment]
@Rkareko 
I have tested this on stage
the upload was successful and also the download was successful
I can also open the downloaded files and see the names
