### ISSUE TITLE
Update Location ID Based on Provided School ID

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#952]
Please add a check on the kids uploaded through the csv on Eswatini, so that the server queries the DB for the correct location ID based on the school ID in the uploaded csv, and updates the location ID data for the uploaded children.

**_Acceptance Criteria_**

Kids uploaded via the CSV upload feature should be visible in the correct school on both the Androip app and Web UI uder each of the following scenario -

1. Upload a CSV with the `location_id` value missing
2. Upload a CSV with the `location_id` having a value that is not the parent location of the school provided

**Comment by madrinekariuki** [comment]
@Rkareko 
This has been tested on reveal stage
APK: V5.3.30-RC8
User:test200
schoolName:Enhletjeni 

find below scenarios tested and observations:
- No locationID details but LocationID column title present
      the kids upload successfully and show on both web and android under Enhletjeni school


- No locationID details and no LocationID column title
    This one returns a Http 400 error and the file does not upload.
    
    
- LocationID for a different school (used for test Lomahasha) 
     The kids show on web and on android under Enhletjeni school

- completely wrong LocationID (i.e belongs to no school)
     file uploads successfully and kids show on web and on android under Enhletjeni school


NB// All the uploaded kids still do not have tasks generated.

**Comment by madrinekariuki** [comment]
This has been tested on production instance
APK: V5.3.30-RC9
User:eswatini10
schoolName:Test Lomahasha - Emafusini Nazarene

find below scenarios tested and observations:

- No locationID details but LocationID column title present
the kids upload successfully and show on both web and android under Test Lomahasha - Emafusini Nazarene school

- No locationID details and no LocationID column title
This one returns a Http 400 error and the file does not upload.

- LocationID for a different school (used for enhletjeni)
The kids show on web and on android under Test Lomahasha - Emafusini Nazarene school

- completely wrong LocationID (i.e belongs to no school)
file uploads successfully and kids show on web and on android under Test Lomahasha - Emafusini Nazarene school

NB// tasks generated for all kids
