### ISSUE TITLE
Deletion of duplicate Plans on Thailand Production OpenSRP DB

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-server-web#959]
There seems to have been duplication of plans in the last attempt to reprocess case triggered plans manually. The plans below have all been found to be duplicate and should be deleted from the Thailand OpenSRP Production DB.

1. 5fc245ff-ad55-48be-8f44-c0a4f8f78b23
2. 976ff742-f314-409d-a969-34963ca8fe0d
3. 3d8c70a2-81f1-4860-b121-e6b7fe0776a2
4. 42dce986-58f0-40cc-a73e-89004cc182a9
5. 45dff529-a004-482a-8a7b-b826b0fea68b
6. d6a2ae2f-c283-4559-a35d-a998981012f5
7. 6789bd52-8aae-474f-b70e-d5d59ba1f376
8. ed2445ec-242a-440e-83c5-6d1562b38ab2
9. de5bc516-93d3-44d6-9e8e-9711db7d5eac
10. bb4afa58-956c-478f-b393-6ffb2c178052
11. 0807cc42-06d6-4239-9c0e-14013a0c4f43
12. 506bcd7e-9fbc-40da-a00f-eff7219393c6
13. f17c3cae-7542-4da6-a0c4-02262f018e03
14. 8e987751-0506-487f-a773-fc9f1b68763b
15. 71debf0c-d7fa-4144-ad84-ff156d136701
16. 16d65570-7796-4f95-ab0c-66b1df861fdb
17. 15c9448a-71aa-4350-b873-97e750cd7118
18. abb28557-64bf-4024-8137-5468dbae1f52
19. 60b3853e-998b-4274-aaf3-625a26eb080e
20. ef9475d4-872c-4794-a891-da284a3c52d3
21. ccec8ff9-694c-49b7-b5a8-712b1a98b8be
22. 46e77801-0aa3-43b4-b378-84c130c6dd30
23. 1400b3ef-af0f-43e4-bd15-f0ab020970e4
24. 2e9425a2-1ac7-43b7-9875-8af66d563610
25. e52f524b-4bdf-4d70-b8c4-4e71a1235863
26. b2168be2-f6d2-436c-99d5-ea7d49f3d840
27. 5a49e21f-7605-4776-8d4c-b785be7f6d78
28. 7a6188a2-23eb-444f-bd06-e6bae33b70dc
29. c88a11a1-61fe-40b9-8431-883e9b599883
30. 390ab86e-90e6-4994-b825-4fc84bf0740e
31. ed8bdf6f-71ca-4e02-afed-45c41501b46a
32. 76a49a0e-3026-466e-98a3-1270fa58b8b8
33. 5a2b2062-71c7-4951-849f-6eb57055130f
34. 297b17f4-7544-4044-9e29-221412732852
35. 2e07b117-7dfc-4222-ba0a-7182f66f9a1f
36. cc480a3f-1def-4e19-aa6d-af2ad6c320c1
37. 75eb0bba-7137-46f9-816a-53e97e499b38
38. bacf8094-3158-4db6-843e-b41a2c5202de
39. af7a1584-61db-4ad0-b3c9-7be5d6756626
40. afcc89d4-f26c-412b-bfe7-95300957096d
41. 2c42e609-5c7a-481f-952c-eedaf4a4cdba
42. 359f8f39-7943-4c26-8081-5c6518c46af3
43. 8f0c4627-a0db-438e-aa9d-98d81f7de625
44. e295a8ac-5b0b-4c89-9a96-7d4289260fd3
45. f0fe32f7-91aa-4eef-a2a2-3a0fdfc262f0
46. 9c11f84e-ee55-4bc0-a802-55d307f3390f
47. 35918c2c-3d95-4dcf-a07f-c00042ebac06
48. 63657a9c-3af6-48ba-8401-481a043bb125
49. 40f76456-74d1-4348-af72-ad810403ba11

**Comment by LZRS** [comment]
@samkanga it's done

**Comment by samkanga** [comment]
@LZRS the client has shared another list for deletion. Note the new list may have some plan IDs already shared above. Below is the list:

**Comment by samkanga** [comment]
@LZRS please also delete this additional list:

1. bc90f116-11eb-42b8-af04-666897e407ae
2. 7a33f53b-ec57-4b34-b474-dea5c88200aa
3. 9853e0cd-a5fa-473c-946a-34ffc317f32a
4. 299b2517-ff74-413e-a65c-c5dc14fa34e2
5. 337fb143-17a1-4509-97a3-378d7d46f554
6. 3fd83360-1b33-45e5-8dfd-2eb7ce407ef5
7. 023d904c-0451-439d-978d-495e67dfe150
8. 2e0c0c71-bfae-4558-ad77-4f915600f30e
9. f0a7b735-f993-4790-b5e9-d68d999d4500
10. f95da4f7-acb1-4bd5-ba88-6226ec51c05d
11. 9cb8f0fa-5b83-4457-b360-b421c22393d6
12. d091607c-87d4-493b-ab22-9fd4fe27c15d
13. 67b0fc12-cb20-416f-885f-5668eb282964
14. 71eb0bff-835a-46bc-bdfd-b86d173b6d53
15. 0e34ca3b-45c2-4d23-a6d2-3a764a79b7e4
16. 1bb51645-0652-4cd4-b2f8-f8849521eda7
17. 449cc043-7396-480a-8802-357986588aa3
18. 4069f3e1-0dad-4d89-8a76-1103ff26807f
19. 5bb6cd98-e12e-4d82-a0fe-5bab905e8fc6
20. 61b8e113-f2f1-4a51-9f83-5a76fd47242a
21. 6ef30d47-ea90-43cd-ab34-9411e544ca66
22. 75c59a27-4919-4a30-8241-8e93fe4757e5
23. 83461ea4-382d-41c6-9954-4c6634b85674
24. d6d8d9f7-5a5e-4249-97bb-86b4fcfb32ff
25. ea1627dc-11b6-4be5-99d4-0f9eea485467
26. b07eb9ce-91a5-432d-b9c8-0df300e7893d
27. bb669c4e-a2b8-402d-b97d-d2bf66fdde19
28. c9b63d8b-2477-48d2-a183-dc32440b3d14
29. 5c35329e-bb25-4e8b-b101-551133e483e9
30. 665517c2-a7c6-45d2-b3e5-acbdeec900f2
31. 67dbdfc1-c13b-42d6-b13d-67eb76bb008d
32. 3169cff1-7e77-4c2a-92e4-9ba2e5d7831f
33. 42ea9452-1ce6-455a-bcab-0403aa338053
34. 411ed0ba-ca98-4390-b5fa-d3791ccd4ef3
35. 45ad426b-78ee-424d-9d3b-47e2e7c7bbab
36. 00922e27-436f-4a89-9fb3-a6f579a493ed
37. 991322a9-ad30-4c56-8070-f290abc65456
38. db6f03ec-89a6-4f56-9867-ef98c4ed2d51
39. e7bcd1b5-0d9b-4cf8-a3a8-8e21cee4ef63
40. c0002130-b7ed-4db5-a8ae-ce9abacf33a8
41. adac6645-f056-4d2c-8a3e-a64d0d21b522
42. a93817a1-ac5e-4d5c-b188-e5fa030018b1
43. f2abb466-c831-4d1a-94be-75c889b07292
44. bb0e37e4-3e65-4af5-8461-8c462f8a4139
45. e14b8c82-9fc8-4c40-a27a-1c46f4dce6d1
46. 204b16fb-9219-43ad-a763-8847f9dd6bb8
47. 114363d4-8ed9-4770-9609-be41a490e3cc
48. 2c29f35b-b79e-4cab-a851-0f2b1900ea10
49. 6683ca27-7cb5-412c-a4f6-cc59b3ef2fc9
50. 6dfbf4f8-9180-47e7-a10b-599cf927968f
51. 5762601b-853d-46aa-a2e5-e794a7f3061a
52. 2e0a8667-ad45-40b2-bc3d-eee4532a102c
53. 2d9694b3-84f7-4718-bea2-d35f43a34f70
54. 2ab92f63-f7df-42df-86be-9d7e37ffa465
55. ef76b8e4-1676-4ded-bd8c-5216f082ccf7
56. bad1080e-5cf4-4dc3-8f7e-4a4657a631d1
57. 4b77cf97-42af-4cbb-a218-b8799364db35
58. 0a5f6cfe-b6b1-4d0b-850c-3632bc7058a1
59. b9c0f10e-a8d8-479d-a47a-cb5a124586c9
60. 4ec4221e-69f1-4d1e-af29-efbbfc0aef97
61. 6681cf46-c6b5-4932-be2c-c86ea7851b32
62. 67f9ba20-f6c8-4894-a88a-c535e0a5e104
63. ff23e3d1-f6c7-48d8-b933-b74790954a41
64. 4c862d72-28aa-4943-b45e-7c686bd9c5ed
65. c611e3ef-3ad6-462e-b51d-fdf6d3ae33b8
66. 43901b42-a5d4-4e49-b568-bf707d3b9af9
67. 4dc3e7ff-7d96-477c-82d9-45fcec993177
68. acd3a16f-756d-4c19-8e63-69d9842c124a
69. a86228e0-5809-4a13-83f9-6215db3537f6
70. 1596c1f0-e1c6-4ce1-8c80-ad4b09627f88
71. cc902bc8-6721-4175-b565-f0c80547845d
72. e3057bf0-5deb-4f88-bb18-2bc4866f3b33
73. c26abbc6-d93b-4907-945a-29b5f875e486
