### ISSUE TITLE
Investigate slow processing of event and client records

### ISSUE THREAD

**Issue by bennsimon** [opensrp/opensrp-server-web#960]
The issue had been noticed on Wcaro flavors which post 250 events + clients to the `/opensrp/rest/event/add` endpoint, it took some minutes to process which resulted to nginx and/or LB timeouts.

**Comment by bennsimon** [comment]
From the investigation done we noticed that some 'search' columns didn't have indices.

We added the indices in these PRs:
- https://github.com/opensrp/opensrp-server-configs/pull/134
- https://github.com/opensrp/opensrp-server-configs/pull/135

**Comment by dubdabasoduba** [comment]
@bennsimon I assume using the latest tags of opensrp would have these changes right?

**Comment by bennsimon** [comment]
yeah
