### ISSUE TITLE
Plans not generating BCC tasks on TH Preview

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-server-web#971]
Newly created plans such as [N/A เมืองทอง(Site)-3 2021-10-13 MK](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/08299398-1f65-597f-a370-86a89033a693) are not generating BCC tasks yet they have a BCC action

When doing QA use a location that has an empty string value such as the one with Id `b8a404d0-5e4d-455f-8bc1-90f8005c3b0a`

**Comment by Rkareko** [comment]
@samkanga It appears some [jurisdictions](https://reveal-th-preview.smartregister.org/opensrp/rest/location/b8a404d0-5e4d-455f-8bc1-90f8005c3b0a?is_jurisdiction=true&return_geometry=false) have an empty value for the `name_en` property i.e 

`{"type":"Feature","id":"b8a404d0-5e4d-455f-8bc1-90f8005c3b0a","properties":{"status":"Active","parentId":"a5167f21-d0ab-4c38-b1b9-f0913de005d4","name":"เมืองทอง(Site)-3","geographicLevel":5,"version":0,"OpenMRS_Id":"1b15db0b-9229-4562-81ca-86a11b777169","externalId":"1206030005","name_en":""},"serverVersion":1600251375766,"locationTags":[{"id":2,"name":"Operational Area"}]}`

During BCC task generation the jurisdiction is fetched from the opensrp db and is converted to a Fhir Resource. A [null check](https://github.com/opensrp/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L64) is done but since the `name_en` field has an empty string value it passes. An exception occurs when that empty string is being converted into an `alias` [here](https://github.com/opensrp/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L65).
At this point an exception is thrown hence BCC tasks are not generated.

**Comment by madrinekariuki** [comment]
BCC tasks are now being generated. this was tested on this new  plan 
N/A เมืองทอง(Site)-2 2021-10-15 KK
see screenshot below. 
![image](https://user-images.githubusercontent.com/84722169/137483423-c4ca0309-a5d7-4e2e-baa1-7e0affe67ed2.png)
